# Generated by oagen. DO NOT EDIT.


from __future__ import annotations

from typing import Any, TypeVar

from pydantic import BaseModel

from .._async_base_client import _AsyncBaseClient
from .._base_client import _BaseClient
from .._models import HealthResponse

_M = TypeVar("_M", bound=BaseModel)


def _coerce(model_cls: type[_M], data: Any) -> _M:
    """Validate API response data into the generated model type."""
    return model_cls.model_validate(data)


class Healthz:
    """Healthz resource."""

    def __init__(self, client: _BaseClient) -> None:
        self._client = client

    def health_check(self) -> HealthResponse:
        """
        Health check

        Returns health status of the service
        """
        path = "/healthz"
        response = self._client._request(method="GET", path=path)
        return _coerce(HealthResponse, response)


class AsyncHealthz:
    """Healthz resource."""

    def __init__(self, client: _AsyncBaseClient) -> None:
        self._client = client

    async def health_check(self) -> HealthResponse:
        """
        Health check

        Returns health status of the service
        """
        path = "/healthz"
        response = await self._client._request(method="GET", path=path)
        return _coerce(HealthResponse, response)
