# Generated by oagen. DO NOT EDIT.


from __future__ import annotations

from typing import Any, TypeVar

from pydantic import BaseModel

from .._async_base_client import _AsyncBaseClient
from .._base_client import _BaseClient
from .._models import ReadinessResponse

_M = TypeVar("_M", bound=BaseModel)


def _coerce(model_cls: type[_M], data: Any) -> _M:
    """Validate API response data into the generated model type."""
    return model_cls.model_validate(data)


class Readyz:
    """Readyz resource."""

    def __init__(self, client: _BaseClient) -> None:
        self._client = client

    def readiness_check(self) -> ReadinessResponse:
        """
        Readiness check

        Returns readiness status with active sandbox count
        """
        path = "/readyz"
        response = self._client._request(method="GET", path=path)
        return _coerce(ReadinessResponse, response)


class AsyncReadyz:
    """Readyz resource."""

    def __init__(self, client: _AsyncBaseClient) -> None:
        self._client = client

    async def readiness_check(self) -> ReadinessResponse:
        """
        Readiness check

        Returns readiness status with active sandbox count
        """
        path = "/readyz"
        response = await self._client._request(method="GET", path=path)
        return _coerce(ReadinessResponse, response)
