# Generated by oagen. DO NOT EDIT.


from __future__ import annotations

from typing import Any, TypeVar

from pydantic import BaseModel

from .._async_base_client import _AsyncBaseClient
from .._base_client import _BaseClient
from .._models import (
    CountResponse,
    CreateResponse,
    ExecRequest,
    ExecResponse,
    ListResponse,
    LogsResponse,
    LookupResult,
    SandboxSpec,
    StatusResponse,
)
from ..enums import SandboxesPhase

_M = TypeVar("_M", bound=BaseModel)


def _coerce(model_cls: type[_M], data: Any) -> _M:
    """Validate API response data into the generated model type."""
    return model_cls.model_validate(data)


class Sandboxes:
    """Sandboxes resource."""

    def __init__(self, client: _BaseClient) -> None:
        self._client = client

    def list_sandboxes(self, start_time: str | None = None, end_time: str | None = None, search: str | None = None, tag: list[str] | None = None, phase: list[SandboxesPhase] | None = None, image: str | None = None, include_filter_values: bool | None = None, page: int | None = None) -> ListResponse:
        """
        List sandboxes

        List sandboxes, optionally filtered by name prefix, exact tag, phase, or image.
        """
        path = "/v1/sandbox"
        params: dict[str, Any] = {}
        if start_time is not None:
            params["start_time"] = start_time
        if end_time is not None:
            params["end_time"] = end_time
        if search is not None:
            params["search"] = search
        if tag is not None:
            params["tag"] = tag
        if phase is not None:
            params["phase"] = phase
        if image is not None:
            params["image"] = image
        if include_filter_values is not None:
            params["include_filter_values"] = include_filter_values
        if page is not None:
            params["page"] = page
        response = self._client._request(method="GET", path=path, params=params)
        return _coerce(ListResponse, response)

    def sandbox_counts(self, start_time: str | None = None, end_time: str | None = None, search: str | None = None, tag: list[str] | None = None, phase: list[SandboxesPhase] | None = None, image: str | None = None) -> CountResponse:
        """
        Count sandboxes over time

        Count sandboxes by creation time, bucketed over a window, using the same
        filters as the list endpoint. Covers only sandboxes the control plane
        still retains.
        """
        path = "/v1/sandbox/counts"
        params: dict[str, Any] = {}
        if start_time is not None:
            params["start_time"] = start_time
        if end_time is not None:
            params["end_time"] = end_time
        if search is not None:
            params["search"] = search
        if tag is not None:
            params["tag"] = tag
        if phase is not None:
            params["phase"] = phase
        if image is not None:
            params["image"] = image
        response = self._client._request(method="GET", path=path, params=params)
        return _coerce(CountResponse, response)

    def create_sandbox(self, body: SandboxSpec) -> CreateResponse:
        """
        Create sandbox

        Create a new sandbox and queue it for execution
        """
        path = "/v1/sandbox/run"
        response = self._client._request(method="POST", path=path, json=body.model_dump(by_alias=True, exclude_none=True) if hasattr(body, "model_dump") else body)
        return _coerce(CreateResponse, response)

    def lookup_sandbox(self, name: str) -> LookupResult:
        """
        Resolve a sandbox name to its id

        Resolve a sandbox name to its id. Names are unique, so this returns at
        most one id. All other sandbox operations address the sandbox by id.
        """
        path = "/v1/sandbox/lookup"
        params: dict[str, Any] = {}
        params["name"] = name
        response = self._client._request(method="GET", path=path, params=params)
        return _coerce(LookupResult, response)

    def get_sandbox(self, id: str) -> StatusResponse:
        """
        Get sandbox status

        Get the current status of a sandbox
        """
        path = f"/v1/sandbox/{id}"
        response = self._client._request(method="GET", path=path)
        return _coerce(StatusResponse, response)

    def delete_sandbox(self, id: str) -> None:
        """
        Terminate sandbox

        Terminate a sandbox and clean up its resources
        """
        path = f"/v1/sandbox/{id}"
        self._client._request(method="DELETE", path=path)
        return None

    def get_sandbox_logs(self, id: str, limit: int | None = None, since: str | None = None) -> LogsResponse:
        """
        Get sandbox logs

        Get logs from a sandbox via Loki. Logs persist after sandbox termination.
        """
        path = f"/v1/sandbox/{id}/logs"
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if since is not None:
            params["since"] = since
        response = self._client._request(method="GET", path=path, params=params)
        return _coerce(LogsResponse, response)

    def exec_sandbox(self, id: str, body: ExecRequest) -> ExecResponse:
        """
        Exec in sandbox

        Run a command in a running sandbox and return its output and exit code
        """
        path = f"/v1/sandbox/{id}/exec"
        response = self._client._request(method="POST", path=path, json=body.model_dump(by_alias=True, exclude_none=True) if hasattr(body, "model_dump") else body)
        return _coerce(ExecResponse, response)


class AsyncSandboxes:
    """Sandboxes resource."""

    def __init__(self, client: _AsyncBaseClient) -> None:
        self._client = client

    async def list_sandboxes(self, start_time: str | None = None, end_time: str | None = None, search: str | None = None, tag: list[str] | None = None, phase: list[SandboxesPhase] | None = None, image: str | None = None, include_filter_values: bool | None = None, page: int | None = None) -> ListResponse:
        """
        List sandboxes

        List sandboxes, optionally filtered by name prefix, exact tag, phase, or image.
        """
        path = "/v1/sandbox"
        params: dict[str, Any] = {}
        if start_time is not None:
            params["start_time"] = start_time
        if end_time is not None:
            params["end_time"] = end_time
        if search is not None:
            params["search"] = search
        if tag is not None:
            params["tag"] = tag
        if phase is not None:
            params["phase"] = phase
        if image is not None:
            params["image"] = image
        if include_filter_values is not None:
            params["include_filter_values"] = include_filter_values
        if page is not None:
            params["page"] = page
        response = await self._client._request(method="GET", path=path, params=params)
        return _coerce(ListResponse, response)

    async def sandbox_counts(self, start_time: str | None = None, end_time: str | None = None, search: str | None = None, tag: list[str] | None = None, phase: list[SandboxesPhase] | None = None, image: str | None = None) -> CountResponse:
        """
        Count sandboxes over time

        Count sandboxes by creation time, bucketed over a window, using the same
        filters as the list endpoint. Covers only sandboxes the control plane
        still retains.
        """
        path = "/v1/sandbox/counts"
        params: dict[str, Any] = {}
        if start_time is not None:
            params["start_time"] = start_time
        if end_time is not None:
            params["end_time"] = end_time
        if search is not None:
            params["search"] = search
        if tag is not None:
            params["tag"] = tag
        if phase is not None:
            params["phase"] = phase
        if image is not None:
            params["image"] = image
        response = await self._client._request(method="GET", path=path, params=params)
        return _coerce(CountResponse, response)

    async def create_sandbox(self, body: SandboxSpec) -> CreateResponse:
        """
        Create sandbox

        Create a new sandbox and queue it for execution
        """
        path = "/v1/sandbox/run"
        response = await self._client._request(method="POST", path=path, json=body.model_dump(by_alias=True, exclude_none=True) if hasattr(body, "model_dump") else body)
        return _coerce(CreateResponse, response)

    async def lookup_sandbox(self, name: str) -> LookupResult:
        """
        Resolve a sandbox name to its id

        Resolve a sandbox name to its id. Names are unique, so this returns at
        most one id. All other sandbox operations address the sandbox by id.
        """
        path = "/v1/sandbox/lookup"
        params: dict[str, Any] = {}
        params["name"] = name
        response = await self._client._request(method="GET", path=path, params=params)
        return _coerce(LookupResult, response)

    async def get_sandbox(self, id: str) -> StatusResponse:
        """
        Get sandbox status

        Get the current status of a sandbox
        """
        path = f"/v1/sandbox/{id}"
        response = await self._client._request(method="GET", path=path)
        return _coerce(StatusResponse, response)

    async def delete_sandbox(self, id: str) -> None:
        """
        Terminate sandbox

        Terminate a sandbox and clean up its resources
        """
        path = f"/v1/sandbox/{id}"
        await self._client._request(method="DELETE", path=path)
        return None

    async def get_sandbox_logs(self, id: str, limit: int | None = None, since: str | None = None) -> LogsResponse:
        """
        Get sandbox logs

        Get logs from a sandbox via Loki. Logs persist after sandbox termination.
        """
        path = f"/v1/sandbox/{id}/logs"
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if since is not None:
            params["since"] = since
        response = await self._client._request(method="GET", path=path, params=params)
        return _coerce(LogsResponse, response)

    async def exec_sandbox(self, id: str, body: ExecRequest) -> ExecResponse:
        """
        Exec in sandbox

        Run a command in a running sandbox and return its output and exit code
        """
        path = f"/v1/sandbox/{id}/exec"
        response = await self._client._request(method="POST", path=path, json=body.model_dump(by_alias=True, exclude_none=True) if hasattr(body, "model_dump") else body)
        return _coerce(ExecResponse, response)
