# Generated by oagen. DO NOT EDIT.


from __future__ import annotations

from typing import Any, TypeVar

from pydantic import BaseModel

from .._async_base_client import _AsyncBaseClient
from .._base_client import _BaseClient
from .._models import Snapshot, SnapshotListResponse, SnapshotSpec

_M = TypeVar("_M", bound=BaseModel)


def _coerce(model_cls: type[_M], data: Any) -> _M:
    """Validate API response data into the generated model type."""
    return model_cls.model_validate(data)


class Snapshots:
    """Snapshots resource."""

    def __init__(self, client: _BaseClient) -> None:
        self._client = client

    def create_snapshot(self, id: str, body: SnapshotSpec) -> Snapshot:
        """
        Snapshot a sandbox

        Capture a running sandbox so a new sandbox can be started from it later.
        The sandbox keeps running.
        """
        path = f"/v1/sandbox/{id}/snapshot"
        response = self._client._request(method="POST", path=path, json=body.model_dump(by_alias=True, exclude_none=True) if hasattr(body, "model_dump") else body)
        return _coerce(Snapshot, response)

    def list_snapshots(self, sandbox_id: str | None = None) -> SnapshotListResponse:
        """
        List snapshots

        List captured snapshots, most recent first.
        """
        path = "/v1/snapshot"
        params: dict[str, Any] = {}
        if sandbox_id is not None:
            params["sandbox_id"] = sandbox_id
        response = self._client._request(method="GET", path=path, params=params)
        return _coerce(SnapshotListResponse, response)

    def delete_snapshot(self, id: str) -> None:
        """
        Delete snapshot

        Delete a snapshot and everything it captured.
        """
        path = f"/v1/snapshot/{id}"
        self._client._request(method="DELETE", path=path)
        return None


class AsyncSnapshots:
    """Snapshots resource."""

    def __init__(self, client: _AsyncBaseClient) -> None:
        self._client = client

    async def create_snapshot(self, id: str, body: SnapshotSpec) -> Snapshot:
        """
        Snapshot a sandbox

        Capture a running sandbox so a new sandbox can be started from it later.
        The sandbox keeps running.
        """
        path = f"/v1/sandbox/{id}/snapshot"
        response = await self._client._request(method="POST", path=path, json=body.model_dump(by_alias=True, exclude_none=True) if hasattr(body, "model_dump") else body)
        return _coerce(Snapshot, response)

    async def list_snapshots(self, sandbox_id: str | None = None) -> SnapshotListResponse:
        """
        List snapshots

        List captured snapshots, most recent first.
        """
        path = "/v1/snapshot"
        params: dict[str, Any] = {}
        if sandbox_id is not None:
            params["sandbox_id"] = sandbox_id
        response = await self._client._request(method="GET", path=path, params=params)
        return _coerce(SnapshotListResponse, response)

    async def delete_snapshot(self, id: str) -> None:
        """
        Delete snapshot

        Delete a snapshot and everything it captured.
        """
        path = f"/v1/snapshot/{id}"
        await self._client._request(method="DELETE", path=path)
        return None
