# Generated by oagen. DO NOT EDIT.


from __future__ import annotations

from typing import Any, TypeVar

from pydantic import BaseModel

from .._async_base_client import _AsyncBaseClient
from .._base_client import _BaseClient
from .._binary import BinaryContent
from .._models import (
    LookupResult,
    Volume,
    VolumeFileListResponse,
    VolumeFileMoveRequest,
    VolumeListResponse,
    VolumeSpec,
)

_M = TypeVar("_M", bound=BaseModel)


def _coerce(model_cls: type[_M], data: Any) -> _M:
    """Validate API response data into the generated model type."""
    return model_cls.model_validate(data)


class Volumes:
    """Volumes resource."""

    def __init__(self, client: _BaseClient) -> None:
        self._client = client

    def list_volumes(self) -> VolumeListResponse:
        """
        List volumes

        List volumes and the sandboxes they are attached to.
        """
        path = "/v1/volume"
        response = self._client._request(method="GET", path=path)
        return _coerce(VolumeListResponse, response)

    def create_volume(self, body: VolumeSpec) -> Volume:
        """
        Create volume

        Create a persistent volume that sandboxes can mount at launch
        """
        path = "/v1/volume"
        response = self._client._request(method="POST", path=path, json=body.model_dump(by_alias=True, exclude_none=True) if hasattr(body, "model_dump") else body)
        return _coerce(Volume, response)

    def lookup_volume(self, name: str) -> LookupResult:
        """
        Resolve a volume name to its id

        Resolve a volume name to its id. Names are unique, so this returns at
        most one id. All other volume operations address the volume by id.
        """
        path = "/v1/volume/lookup"
        params: dict[str, Any] = {}
        params["name"] = name
        response = self._client._request(method="GET", path=path, params=params)
        return _coerce(LookupResult, response)

    def get_volume(self, id: str) -> Volume:
        """
        Get volume

        Get a volume and the sandboxes it is attached to
        """
        path = f"/v1/volume/{id}"
        response = self._client._request(method="GET", path=path)
        return _coerce(Volume, response)

    def delete_volume(self, id: str) -> None:
        """
        Delete volume

        Delete a volume. Fails while the volume is attached to a sandbox.
        """
        path = f"/v1/volume/{id}"
        self._client._request(method="DELETE", path=path)
        return None

    def list_volume_files(self, id: str, path: str | None = None, search: str | None = None) -> VolumeFileListResponse:
        """
        List volume files

        List the files and directories under a path inside a volume, read from
        the shared sandbox volumes mount. The listing walks the tree
        breadth-first up to a server-side entry budget: small trees come back
        complete in one response, and directories the walk did not fully read
        are marked truncated for clients to list directly. Requires the control
        plane to have the mount configured; without it every listing reports
        the files API as unavailable.
        """
        path_ = f"/v1/volume/{id}/files"
        params: dict[str, Any] = {}
        if path is not None:
            params["path"] = path
        if search is not None:
            params["search"] = search
        response = self._client._request(method="GET", path=path_, params=params)
        return _coerce(VolumeFileListResponse, response)

    def read_volume_file(self, id: str, path: str, range: str | None = None, timeout: float | None = None) -> BinaryContent:
        """
        Read volume file

        Stream a file's raw bytes from a volume. The response is the file
        content itself, so clients bound how much they read: send a single
        byte range (e.g. bytes=0-1048575) to read part of the file, or omit
        the Range header for the whole file.
        """
        path_ = f"/v1/volume/{id}/files/content"
        params: dict[str, Any] = {}
        params["path"] = path
        response: BinaryContent = self._client._request_binary(method="GET", path=path_, params=params, headers={"Range": range}, timeout=timeout)
        return response

    def write_volume_file(self, id: str, body: bytes, path: str, timeout: float | None = None) -> None:
        """
        Write volume file

        Write a file to a volume, replacing whatever is at the path and creating
        parent directories as needed. The request body is the file's raw bytes,
        of any size. The write is only visible at the path once the whole body
        has been received, so an upload that fails partway leaves the previous
        content in place rather than a truncated file.
        """
        path_ = f"/v1/volume/{id}/files/content"
        params: dict[str, Any] = {}
        params["path"] = path
        self._client._request(method="PUT", path=path_, params=params, content=body, content_type="application/octet-stream", timeout=timeout)
        return None

    def move_volume_file(self, id: str, body: VolumeFileMoveRequest) -> None:
        """
        Move volume file

        Move or rename a file or directory inside a volume. The destination is
        the entry's full new path, so one call covers both renaming in place and
        relocating into another directory, and a directory moves with everything
        under it. The destination's parent directory must already exist, and a
        move onto a path something is already at is refused rather than
        overwriting it.
        """
        path = f"/v1/volume/{id}/files/move"
        self._client._request(method="POST", path=path, json=body.model_dump(by_alias=True, exclude_none=True) if hasattr(body, "model_dump") else body)
        return None


class AsyncVolumes:
    """Volumes resource."""

    def __init__(self, client: _AsyncBaseClient) -> None:
        self._client = client

    async def list_volumes(self) -> VolumeListResponse:
        """
        List volumes

        List volumes and the sandboxes they are attached to.
        """
        path = "/v1/volume"
        response = await self._client._request(method="GET", path=path)
        return _coerce(VolumeListResponse, response)

    async def create_volume(self, body: VolumeSpec) -> Volume:
        """
        Create volume

        Create a persistent volume that sandboxes can mount at launch
        """
        path = "/v1/volume"
        response = await self._client._request(method="POST", path=path, json=body.model_dump(by_alias=True, exclude_none=True) if hasattr(body, "model_dump") else body)
        return _coerce(Volume, response)

    async def lookup_volume(self, name: str) -> LookupResult:
        """
        Resolve a volume name to its id

        Resolve a volume name to its id. Names are unique, so this returns at
        most one id. All other volume operations address the volume by id.
        """
        path = "/v1/volume/lookup"
        params: dict[str, Any] = {}
        params["name"] = name
        response = await self._client._request(method="GET", path=path, params=params)
        return _coerce(LookupResult, response)

    async def get_volume(self, id: str) -> Volume:
        """
        Get volume

        Get a volume and the sandboxes it is attached to
        """
        path = f"/v1/volume/{id}"
        response = await self._client._request(method="GET", path=path)
        return _coerce(Volume, response)

    async def delete_volume(self, id: str) -> None:
        """
        Delete volume

        Delete a volume. Fails while the volume is attached to a sandbox.
        """
        path = f"/v1/volume/{id}"
        await self._client._request(method="DELETE", path=path)
        return None

    async def list_volume_files(self, id: str, path: str | None = None, search: str | None = None) -> VolumeFileListResponse:
        """
        List volume files

        List the files and directories under a path inside a volume, read from
        the shared sandbox volumes mount. The listing walks the tree
        breadth-first up to a server-side entry budget: small trees come back
        complete in one response, and directories the walk did not fully read
        are marked truncated for clients to list directly. Requires the control
        plane to have the mount configured; without it every listing reports
        the files API as unavailable.
        """
        path_ = f"/v1/volume/{id}/files"
        params: dict[str, Any] = {}
        if path is not None:
            params["path"] = path
        if search is not None:
            params["search"] = search
        response = await self._client._request(method="GET", path=path_, params=params)
        return _coerce(VolumeFileListResponse, response)

    async def read_volume_file(self, id: str, path: str, range: str | None = None, timeout: float | None = None) -> BinaryContent:
        """
        Read volume file

        Stream a file's raw bytes from a volume. The response is the file
        content itself, so clients bound how much they read: send a single
        byte range (e.g. bytes=0-1048575) to read part of the file, or omit
        the Range header for the whole file.
        """
        path_ = f"/v1/volume/{id}/files/content"
        params: dict[str, Any] = {}
        params["path"] = path
        response: BinaryContent = await self._client._request_binary(method="GET", path=path_, params=params, headers={"Range": range}, timeout=timeout)
        return response

    async def write_volume_file(self, id: str, body: bytes, path: str, timeout: float | None = None) -> None:
        """
        Write volume file

        Write a file to a volume, replacing whatever is at the path and creating
        parent directories as needed. The request body is the file's raw bytes,
        of any size. The write is only visible at the path once the whole body
        has been received, so an upload that fails partway leaves the previous
        content in place rather than a truncated file.
        """
        path_ = f"/v1/volume/{id}/files/content"
        params: dict[str, Any] = {}
        params["path"] = path
        await self._client._request(method="PUT", path=path_, params=params, content=body, content_type="application/octet-stream", timeout=timeout)
        return None

    async def move_volume_file(self, id: str, body: VolumeFileMoveRequest) -> None:
        """
        Move volume file

        Move or rename a file or directory inside a volume. The destination is
        the entry's full new path, so one call covers both renaming in place and
        relocating into another directory, and a directory moves with everything
        under it. The destination's parent directory must already exist, and a
        move onto a path something is already at is refused rather than
        overwriting it.
        """
        path = f"/v1/volume/{id}/files/move"
        await self._client._request(method="POST", path=path, json=body.model_dump(by_alias=True, exclude_none=True) if hasattr(body, "model_dump") else body)
        return None
