# Generated by oagen. DO NOT EDIT.


from __future__ import annotations

from typing import Any, TypeVar

from pydantic import BaseModel

from .._async_base_client import _AsyncBaseClient
from .._base_client import _BaseClient
from .._models import LookupResult, Volume, VolumeListResponse, VolumeSpec

_M = TypeVar("_M", bound=BaseModel)


def _coerce(model_cls: type[_M], data: Any) -> _M:
    """Validate API response data into the generated model type."""
    return model_cls.model_validate(data)


class Volumes:
    """Volumes resource."""

    def __init__(self, client: _BaseClient) -> None:
        self._client = client

    def list_volumes(self) -> VolumeListResponse:
        """
        List volumes

        List volumes and the sandboxes they are attached to.
        """
        path = "/v1/volume"
        response = self._client._request(method="GET", path=path)
        return _coerce(VolumeListResponse, response)

    def create_volume(self, body: VolumeSpec) -> Volume:
        """
        Create volume

        Create a persistent volume that sandboxes can mount at launch
        """
        path = "/v1/volume"
        response = self._client._request(method="POST", path=path, json=body.model_dump(by_alias=True, exclude_none=True) if hasattr(body, "model_dump") else body)
        return _coerce(Volume, response)

    def lookup_volume(self, name: str) -> LookupResult:
        """
        Resolve a volume name to its id

        Resolve a volume name to its id. Names are unique, so this returns at
        most one id. All other volume operations address the volume by id.
        """
        path = "/v1/volume/lookup"
        params: dict[str, Any] = {}
        params["name"] = name
        response = self._client._request(method="GET", path=path, params=params)
        return _coerce(LookupResult, response)

    def get_volume(self, id: str) -> Volume:
        """
        Get volume

        Get a volume and the sandboxes it is attached to
        """
        path = f"/v1/volume/{id}"
        response = self._client._request(method="GET", path=path)
        return _coerce(Volume, response)

    def delete_volume(self, id: str) -> None:
        """
        Delete volume

        Delete a volume. Fails while the volume is attached to a sandbox.
        """
        path = f"/v1/volume/{id}"
        self._client._request(method="DELETE", path=path)
        return None


class AsyncVolumes:
    """Volumes resource."""

    def __init__(self, client: _AsyncBaseClient) -> None:
        self._client = client

    async def list_volumes(self) -> VolumeListResponse:
        """
        List volumes

        List volumes and the sandboxes they are attached to.
        """
        path = "/v1/volume"
        response = await self._client._request(method="GET", path=path)
        return _coerce(VolumeListResponse, response)

    async def create_volume(self, body: VolumeSpec) -> Volume:
        """
        Create volume

        Create a persistent volume that sandboxes can mount at launch
        """
        path = "/v1/volume"
        response = await self._client._request(method="POST", path=path, json=body.model_dump(by_alias=True, exclude_none=True) if hasattr(body, "model_dump") else body)
        return _coerce(Volume, response)

    async def lookup_volume(self, name: str) -> LookupResult:
        """
        Resolve a volume name to its id

        Resolve a volume name to its id. Names are unique, so this returns at
        most one id. All other volume operations address the volume by id.
        """
        path = "/v1/volume/lookup"
        params: dict[str, Any] = {}
        params["name"] = name
        response = await self._client._request(method="GET", path=path, params=params)
        return _coerce(LookupResult, response)

    async def get_volume(self, id: str) -> Volume:
        """
        Get volume

        Get a volume and the sandboxes it is attached to
        """
        path = f"/v1/volume/{id}"
        response = await self._client._request(method="GET", path=path)
        return _coerce(Volume, response)

    async def delete_volume(self, id: str) -> None:
        """
        Delete volume

        Delete a volume. Fails while the volume is attached to a sandbox.
        """
        path = f"/v1/volume/{id}"
        await self._client._request(method="DELETE", path=path)
        return None
