# Generated by oagen. DO NOT EDIT.


from __future__ import annotations

from porter_sandbox._models import (
    CountPoint,
    CountResponse,
    CreateResponse,
    Error,
    ExecRequest,
    ExecResponse,
    ExecTarget,
    FilterValuesResponse,
    HealthResponse,
    LogsResponse,
    LookupResult,
    Pagination,
    ReadinessResponse,
    SandboxSpec,
    VolumeListResponse,
    VolumeSpec,
)


def test_count_point_round_trip() -> None:
    instance = CountPoint(timestamp="x", count=1)
    serialized = instance.model_dump(by_alias=True, exclude_none=True)
    round_tripped = CountPoint.model_validate(serialized)
    assert round_tripped.model_dump(by_alias=True, exclude_none=True) == serialized


def test_count_response_round_trip() -> None:
    instance = CountResponse(points=[], granularity_ms=1)
    serialized = instance.model_dump(by_alias=True, exclude_none=True)
    round_tripped = CountResponse.model_validate(serialized)
    assert round_tripped.model_dump(by_alias=True, exclude_none=True) == serialized


def test_create_response_round_trip() -> None:
    instance = CreateResponse(id="x", name="x")
    serialized = instance.model_dump(by_alias=True, exclude_none=True)
    round_tripped = CreateResponse.model_validate(serialized)
    assert round_tripped.model_dump(by_alias=True, exclude_none=True) == serialized


def test_error_round_trip() -> None:
    instance = Error(error="x")
    serialized = instance.model_dump(by_alias=True, exclude_none=True)
    round_tripped = Error.model_validate(serialized)
    assert round_tripped.model_dump(by_alias=True, exclude_none=True) == serialized


def test_exec_request_round_trip() -> None:
    instance = ExecRequest(command=[])
    serialized = instance.model_dump(by_alias=True, exclude_none=True)
    round_tripped = ExecRequest.model_validate(serialized)
    assert round_tripped.model_dump(by_alias=True, exclude_none=True) == serialized


def test_exec_response_round_trip() -> None:
    instance = ExecResponse(stdout="x", stderr="x", exit_code=1)
    serialized = instance.model_dump(by_alias=True, exclude_none=True)
    round_tripped = ExecResponse.model_validate(serialized)
    assert round_tripped.model_dump(by_alias=True, exclude_none=True) == serialized


def test_exec_target_round_trip() -> None:
    instance = ExecTarget(namespace="x", pod_name="x", container_name="x")
    serialized = instance.model_dump(by_alias=True, exclude_none=True)
    round_tripped = ExecTarget.model_validate(serialized)
    assert round_tripped.model_dump(by_alias=True, exclude_none=True) == serialized


def test_filter_values_response_round_trip() -> None:
    instance = FilterValuesResponse(tags=[], images=[], phases=[])
    serialized = instance.model_dump(by_alias=True, exclude_none=True)
    round_tripped = FilterValuesResponse.model_validate(serialized)
    assert round_tripped.model_dump(by_alias=True, exclude_none=True) == serialized


def test_health_response_round_trip() -> None:
    instance = HealthResponse(status="x")
    serialized = instance.model_dump(by_alias=True, exclude_none=True)
    round_tripped = HealthResponse.model_validate(serialized)
    assert round_tripped.model_dump(by_alias=True, exclude_none=True) == serialized


def test_logs_response_round_trip() -> None:
    instance = LogsResponse(sandbox_id="x", logs=[])
    serialized = instance.model_dump(by_alias=True, exclude_none=True)
    round_tripped = LogsResponse.model_validate(serialized)
    assert round_tripped.model_dump(by_alias=True, exclude_none=True) == serialized


def test_lookup_result_round_trip() -> None:
    instance = LookupResult(id="x")
    serialized = instance.model_dump(by_alias=True, exclude_none=True)
    round_tripped = LookupResult.model_validate(serialized)
    assert round_tripped.model_dump(by_alias=True, exclude_none=True) == serialized


def test_pagination_round_trip() -> None:
    instance = Pagination(current_page=1, total_pages=1, has_next_page=True)
    serialized = instance.model_dump(by_alias=True, exclude_none=True)
    round_tripped = Pagination.model_validate(serialized)
    assert round_tripped.model_dump(by_alias=True, exclude_none=True) == serialized


def test_readiness_response_round_trip() -> None:
    instance = ReadinessResponse(status="x", active_sandboxes=1)
    serialized = instance.model_dump(by_alias=True, exclude_none=True)
    round_tripped = ReadinessResponse.model_validate(serialized)
    assert round_tripped.model_dump(by_alias=True, exclude_none=True) == serialized


def test_sandbox_spec_round_trip() -> None:
    instance = SandboxSpec(image="x")
    serialized = instance.model_dump(by_alias=True, exclude_none=True)
    round_tripped = SandboxSpec.model_validate(serialized)
    assert round_tripped.model_dump(by_alias=True, exclude_none=True) == serialized


def test_volume_list_response_round_trip() -> None:
    instance = VolumeListResponse(volumes=[])
    serialized = instance.model_dump(by_alias=True, exclude_none=True)
    round_tripped = VolumeListResponse.model_validate(serialized)
    assert round_tripped.model_dump(by_alias=True, exclude_none=True) == serialized


def test_volume_spec_round_trip() -> None:
    instance = VolumeSpec()
    serialized = instance.model_dump(by_alias=True, exclude_none=True)
    round_tripped = VolumeSpec.model_validate(serialized)
    assert round_tripped.model_dump(by_alias=True, exclude_none=True) == serialized
