# Generated by oagen. DO NOT EDIT.


from __future__ import annotations

from collections.abc import AsyncIterator, Mapping
from typing import Any

import httpx
from httpx._client import UseClientDefault

from ._base_client import (
    MAX_REDIRECTS,
    _decode_body,
    _error_message,
    _origin,
    _redirect_target,
    _request_headers,
    _rewind,
)
from ._binary import BinaryBody, BinaryContent, _binary_content
from ._config import Config
from ._errors import SandboxError, SandboxTimeoutError, error_for_status
from ._retries import DEFAULT_MAX_RETRIES, should_retry, sleep_for_attempt

USER_AGENT = "porter-sandbox-python/0.0.1"


# An async client cannot send a file object directly, so a stream body is read
# through this. The caller's file is rewound first, so each hop reads all of it.
_STREAM_CHUNK_BYTES = 1024 * 1024


def _as_async_stream(content: BinaryBody | None) -> Any:
    """Wrap a file object so an async client can send it, and pass bytes through."""
    read = getattr(content, "read", None)
    if read is None:
        return content

    async def chunks() -> AsyncIterator[bytes]:
        while True:
            chunk = read(_STREAM_CHUNK_BYTES)
            if not chunk:
                break
            yield chunk

    return chunks()


class _AsyncBaseClient:
    """Async HTTP transport shared by all generated async resource classes.

    Owns the httpx.AsyncClient, header injection, retry loop, and error mapping.
    Resource methods call `await self._client._request(...)`, or
    `_request_binary(...)` for the endpoints that answer with bytes rather than
    JSON.
    """

    def __init__(
        self,
        *,
        config: Config,
        max_retries: int = DEFAULT_MAX_RETRIES,
        verify: bool | str = True,
    ) -> None:
        self._config = config
        self._max_retries = max_retries
        headers = {"User-Agent": USER_AGENT}
        if config.api_key:
            headers["Authorization"] = f"Bearer {config.api_key}"
        self._http = httpx.AsyncClient(
            base_url=config.base_url,
            timeout=config.timeout,
            verify=verify,
            headers=headers,
            # _send_following_redirects follows them instead, so a stream
            # body starts over on each hop.
            follow_redirects=False,
        )

    async def __aenter__(self) -> _AsyncBaseClient:
        return self

    async def __aexit__(self, *_exc: object) -> None:
        await self.aclose()

    async def aclose(self) -> None:
        await self._http.aclose()

    async def _send_following_redirects(
        self,
        *,
        method: str,
        url: str,
        params: Mapping[str, Any] | None,
        json: Any,
        content: BinaryBody | None,
        headers: Mapping[str, str],
        timeout: float | None | UseClientDefault,
    ) -> httpx.Response:
        """Send one attempt, and follow any redirect it answers with.

        The API answers a volume file write with a 307, which keeps the method
        and the body. A hop that leaves the origin drops the credentials that
        were meant for that origin.
        """
        target: str | httpx.URL = url
        hop_params = params

        for _ in range(MAX_REDIRECTS + 1):
            _rewind(content)
            request = self._http.build_request(
                method=method,
                url=target,
                params=hop_params,
                json=json,
                content=_as_async_stream(content),
                headers=headers,
                timeout=timeout,
            )
            if isinstance(target, httpx.URL) and _origin(target) != _origin(self._http.base_url):
                request.headers.pop("Authorization", None)
            response = await self._http.send(request)

            redirect = _redirect_target(response)
            if redirect is None:
                return response
            # The redirect target carries its own query already.
            hop_params = None
            target = redirect

        raise SandboxError(f"Too many redirects for {url}")

    async def _request(
        self,
        *,
        method: str,
        path: str,
        params: Mapping[str, Any] | None = None,
        json: Any = None,
        content: BinaryBody | None = None,
        content_type: str | None = None,
        headers: Mapping[str, str | None] | None = None,
        timeout: float | None | UseClientDefault = httpx.USE_CLIENT_DEFAULT,
        retry: bool = True,
    ) -> Any:
        response = await self._send(
            method=method,
            path=path,
            params=params,
            json=json,
            content=content,
            content_type=content_type,
            headers=headers,
            accept="application/json",
            timeout=timeout,
            retry=retry,
        )
        return _decode_body(response)

    async def _request_binary(
        self,
        *,
        method: str,
        path: str,
        params: Mapping[str, Any] | None = None,
        headers: Mapping[str, str | None] | None = None,
        timeout: float | None | UseClientDefault = httpx.USE_CLIENT_DEFAULT,
    ) -> BinaryContent:
        response = await self._send(
            method=method,
            path=path,
            params=params,
            json=None,
            headers=headers,
            accept="application/octet-stream",
            timeout=timeout,
        )
        return _binary_content(response)

    async def _send(
        self,
        *,
        method: str,
        path: str,
        params: Mapping[str, Any] | None,
        json: Any,
        headers: Mapping[str, str | None] | None,
        accept: str,
        content: BinaryBody | None = None,
        content_type: str | None = None,
        timeout: float | None | UseClientDefault = httpx.USE_CLIENT_DEFAULT,
        retry: bool = True,
    ) -> httpx.Response:
        # `timeout=None` disables the timeout, for a call the API works on for
        # the full duration of the request. `retry=False` is for a call that
        # must not be re-sent, because a failed attempt may have run
        # server-side.
        max_retries = self._max_retries if retry else 0
        last_error: Exception | None = None

        for attempt in range(max_retries + 1):
            try:
                response = await self._send_following_redirects(
                    method=method,
                    url=path,
                    params=params,
                    json=json,
                    content=content,
                    headers=_request_headers(headers, accept, content_type),
                    timeout=timeout,
                )
            except httpx.TimeoutException as exc:
                # A timed-out request may have executed server-side, so
                # retrying could run it again. Surface the timeout instead.
                effective = self._config.timeout if timeout is httpx.USE_CLIENT_DEFAULT else timeout
                raise SandboxTimeoutError(f"Request timed out after {effective}s") from exc
            except httpx.HTTPError as exc:
                last_error = exc
                if attempt < max_retries:
                    await sleep_for_attempt(attempt)
                    continue
                raise SandboxError(f"Network error: {exc}") from exc

            if 200 <= response.status_code < 300:
                return response

            if should_retry(response.status_code) and attempt < max_retries:
                await sleep_for_attempt(attempt)
                continue

            body = _decode_body(response)
            raise error_for_status(
                response.status_code,
                body,
                _error_message(body, response.status_code),
            )

        # Unreachable: loop either returns or raises on every path.
        raise SandboxError(f"Request failed after retries: {last_error}")
