# Generated by oagen. DO NOT EDIT.


from __future__ import annotations

import json as json_lib
from collections.abc import Mapping
from typing import Any

import httpx
from httpx._client import UseClientDefault

from ._binary import BinaryBody, BinaryContent, _binary_content
from ._config import Config
from ._errors import SandboxError, SandboxTimeoutError, error_for_status
from ._retries import DEFAULT_MAX_RETRIES, should_retry, sleep_for_attempt_sync

USER_AGENT = "porter-sandbox-python/0.0.1"


# httpx cannot restart a stream body on its own redirect path, so the client
# follows redirects itself and starts the body over on each hop.
_REDIRECT_STATUSES = frozenset({301, 302, 303, 307, 308})
MAX_REDIRECTS = 5


def _rewind(content: BinaryBody | None) -> None:
    """Put a stream body back to the start, so the next send reads all of it."""
    seek = getattr(content, "seek", None)
    if seek is not None:
        seek(0)


def _origin(url: httpx.URL) -> tuple[str, str | None, int | None]:
    """The scheme, host and port a credential belongs to."""
    return (url.scheme, url.host, url.port)


def _redirect_target(response: httpx.Response) -> httpx.URL | None:
    """The URL a response redirects to, or None when it does not redirect."""
    if response.status_code not in _REDIRECT_STATUSES:
        return None
    location = response.headers.get("location")
    return response.url.join(location) if location else None


def _decode_body(response: httpx.Response) -> Any:
    if response.status_code == 204 or not response.content:
        return None
    content_type = response.headers.get("content-type", "")
    if "application/json" in content_type:
        try:
            return response.json()
        except json_lib.JSONDecodeError:
            return response.text
    return response.text


def _error_message(body: Any, status_code: int) -> str:
    if isinstance(body, dict):
        error = body.get("error")
        if isinstance(error, str):
            return error
    return f"HTTP {status_code}"


def _request_headers(
    headers: Mapping[str, str | None] | None, accept: str, content_type: str | None = None
) -> dict[str, str]:
    sent = {"Accept": accept}
    if content_type is not None:
        sent["Content-Type"] = content_type
    for name, value in (headers or {}).items():
        if value is not None:
            sent[name] = value
    return sent


class _BaseClient:
    """Sync HTTP transport shared by all generated sync resource classes.

    Owns the httpx.Client, header injection, retry loop, and error mapping.
    Resource methods call `self._client._request(...)`, or `_request_binary(...)`
    for the endpoints that answer with bytes rather than JSON.
    """

    def __init__(
        self,
        *,
        config: Config,
        max_retries: int = DEFAULT_MAX_RETRIES,
        verify: bool | str = True,
    ) -> None:
        self._config = config
        self._max_retries = max_retries
        headers = {"User-Agent": USER_AGENT}
        if config.api_key:
            headers["Authorization"] = f"Bearer {config.api_key}"
        self._http = httpx.Client(
            base_url=config.base_url,
            timeout=config.timeout,
            verify=verify,
            headers=headers,
            # _send_following_redirects follows them instead, so a stream
            # body starts over on each hop.
            follow_redirects=False,
        )

    def __enter__(self) -> _BaseClient:
        return self

    def __exit__(self, *_exc: object) -> None:
        self.close()

    def close(self) -> None:
        self._http.close()

    def _send_following_redirects(
        self,
        *,
        method: str,
        url: str,
        params: Mapping[str, Any] | None,
        json: Any,
        content: BinaryBody | None,
        headers: Mapping[str, str],
        timeout: float | None | UseClientDefault,
    ) -> httpx.Response:
        """Send one attempt, and follow any redirect it answers with.

        The API answers a volume file write with a 307, which keeps the method
        and the body. A hop that leaves the origin drops the credentials that
        were meant for that origin.
        """
        target: str | httpx.URL = url
        hop_params = params

        for _ in range(MAX_REDIRECTS + 1):
            _rewind(content)
            request = self._http.build_request(
                method=method,
                url=target,
                params=hop_params,
                json=json,
                content=content,
                headers=headers,
                timeout=timeout,
            )
            if isinstance(target, httpx.URL) and _origin(target) != _origin(self._http.base_url):
                request.headers.pop("Authorization", None)
            response = self._http.send(request)

            redirect = _redirect_target(response)
            if redirect is None:
                return response
            # The redirect target carries its own query already.
            hop_params = None
            target = redirect

        raise SandboxError(f"Too many redirects for {url}")

    def _request(
        self,
        *,
        method: str,
        path: str,
        params: Mapping[str, Any] | None = None,
        json: Any = None,
        content: BinaryBody | None = None,
        content_type: str | None = None,
        headers: Mapping[str, str | None] | None = None,
        timeout: float | None | UseClientDefault = httpx.USE_CLIENT_DEFAULT,
        retry: bool = True,
    ) -> Any:
        response = self._send(
            method=method,
            path=path,
            params=params,
            json=json,
            content=content,
            content_type=content_type,
            headers=headers,
            accept="application/json",
            timeout=timeout,
            retry=retry,
        )
        return _decode_body(response)

    def _request_binary(
        self,
        *,
        method: str,
        path: str,
        params: Mapping[str, Any] | None = None,
        headers: Mapping[str, str | None] | None = None,
        timeout: float | None | UseClientDefault = httpx.USE_CLIENT_DEFAULT,
    ) -> BinaryContent:
        response = self._send(
            method=method,
            path=path,
            params=params,
            json=None,
            headers=headers,
            accept="application/octet-stream",
            timeout=timeout,
        )
        return _binary_content(response)

    def _send(
        self,
        *,
        method: str,
        path: str,
        params: Mapping[str, Any] | None,
        json: Any,
        headers: Mapping[str, str | None] | None,
        accept: str,
        content: BinaryBody | None = None,
        content_type: str | None = None,
        timeout: float | None | UseClientDefault = httpx.USE_CLIENT_DEFAULT,
        retry: bool = True,
    ) -> httpx.Response:
        # `timeout=None` disables the timeout, for a call the API works on for
        # the full duration of the request. `retry=False` is for a call that
        # must not be re-sent, because a failed attempt may have run
        # server-side.
        max_retries = self._max_retries if retry else 0
        last_error: Exception | None = None

        for attempt in range(max_retries + 1):
            try:
                response = self._send_following_redirects(
                    method=method,
                    url=path,
                    params=params,
                    json=json,
                    content=content,
                    headers=_request_headers(headers, accept, content_type),
                    timeout=timeout,
                )
            except httpx.TimeoutException as exc:
                # A timed-out request may have executed server-side, so
                # retrying could run it again. Surface the timeout instead.
                effective = self._config.timeout if timeout is httpx.USE_CLIENT_DEFAULT else timeout
                raise SandboxTimeoutError(f"Request timed out after {effective}s") from exc
            except httpx.HTTPError as exc:
                last_error = exc
                if attempt < max_retries:
                    sleep_for_attempt_sync(attempt)
                    continue
                raise SandboxError(f"Network error: {exc}") from exc

            if 200 <= response.status_code < 300:
                return response

            if should_retry(response.status_code) and attempt < max_retries:
                sleep_for_attempt_sync(attempt)
                continue

            body = _decode_body(response)
            raise error_for_status(
                response.status_code,
                body,
                _error_message(body, response.status_code),
            )

        # Unreachable: loop either returns or raises on every path.
        raise SandboxError(f"Request failed after retries: {last_error}")
