# Generated by oagen. DO NOT EDIT.


from __future__ import annotations

import re
from dataclasses import dataclass
from datetime import datetime
from email.utils import parsedate_to_datetime

import httpx

# `bytes 0-1023/8192`. Absent on a whole-file response.
_CONTENT_RANGE_RE = re.compile(r"^bytes (\d+)-(\d+)/(\d+)$")


@dataclass(frozen=True)
class ContentRange:
    """A byte range within a file, read back from a response's Content-Range header."""

    start: int
    end: int
    size: int


@dataclass(frozen=True)
class BinaryContent:
    """Raw bytes from an octet-stream endpoint, with the metadata needed to read a file in pieces."""

    data: bytes
    # Which bytes of the file arrived and how large the file is, set when the
    # request asked for a range.
    content_range: ContentRange | None
    last_modified: datetime | None


def _parse_content_range(header: str | None) -> ContentRange | None:
    match = _CONTENT_RANGE_RE.match(header) if header else None
    if match is None:
        return None
    return ContentRange(start=int(match[1]), end=int(match[2]), size=int(match[3]))


def _parse_http_date(header: str | None) -> datetime | None:
    if not header:
        return None
    try:
        return parsedate_to_datetime(header)
    except (TypeError, ValueError):
        return None


def _binary_content(response: httpx.Response) -> BinaryContent:
    return BinaryContent(
        data=response.content,
        content_range=_parse_content_range(response.headers.get("content-range")),
        last_modified=_parse_http_date(response.headers.get("last-modified")),
    )
