# Generated by oagen. DO NOT EDIT.


from __future__ import annotations

from ._async_base_client import _AsyncBaseClient
from ._base_client import _BaseClient
from ._config import Config
from .resources.healthz import AsyncHealthz, Healthz
from .resources.readyz import AsyncReadyz, Readyz
from .resources.sandboxes import AsyncSandboxes, Sandboxes
from .resources.volumes import AsyncVolumes, Volumes


class PorterSandboxApiClient:
    """Low-level client for the Porter sandbox API."""

    def __init__(
        self,
        *,
        api_key: str | None = None,
        base_url: str | None = None,
        timeout: float | None = None,
    ) -> None:
        self._base = _BaseClient(
            config=Config.resolve(api_key=api_key, base_url=base_url, timeout=timeout),
        )
        self.sandboxes: Sandboxes = Sandboxes(self._base)
        self.volumes: Volumes = Volumes(self._base)
        self.healthz: Healthz = Healthz(self._base)
        self.readyz: Readyz = Readyz(self._base)

    def __enter__(self) -> PorterSandboxApiClient:
        self._base.__enter__()
        return self

    def __exit__(self, *exc: object) -> None:
        self._base.__exit__(*exc)

    def close(self) -> None:
        self._base.close()


class AsyncPorterSandboxApiClient:
    """Async low-level client for the Porter sandbox API."""

    def __init__(
        self,
        *,
        api_key: str | None = None,
        base_url: str | None = None,
        timeout: float | None = None,
    ) -> None:
        self._base = _AsyncBaseClient(
            config=Config.resolve(api_key=api_key, base_url=base_url, timeout=timeout),
        )
        self.sandboxes: AsyncSandboxes = AsyncSandboxes(self._base)
        self.volumes: AsyncVolumes = AsyncVolumes(self._base)
        self.healthz: AsyncHealthz = AsyncHealthz(self._base)
        self.readyz: AsyncReadyz = AsyncReadyz(self._base)

    async def __aenter__(self) -> AsyncPorterSandboxApiClient:
        await self._base.__aenter__()
        return self

    async def __aexit__(self, *exc: object) -> None:
        await self._base.__aexit__(*exc)

    async def aclose(self) -> None:
        await self._base.aclose()
