# Generated by oagen. DO NOT EDIT.


from __future__ import annotations


class SandboxError(Exception):
    """Base class for all Porter sandbox SDK errors."""

    def __init__(self, message: str, *, status_code: int | None = None, body: object | None = None) -> None:
        super().__init__(message)
        self.message = message
        self.status_code = status_code
        self.body = body


class AuthenticationError(SandboxError):
    """Raised when the API rejects credentials (401)."""


class NotFoundError(SandboxError):
    """Raised when a sandbox or other resource cannot be found (404)."""


class RateLimitError(SandboxError):
    """Raised when the API responds with 429 Too Many Requests."""


class ServerError(SandboxError):
    """Raised on 5xx responses from the API."""


class SandboxTimeoutError(SandboxError):
    """Raised when a request exceeds its timeout.

    Never retried by the client: the server may still be executing the request
    (e.g. a long-running exec), so a retry could run it again.
    """


def error_for_status(status_code: int, body: object | None, message: str) -> SandboxError:
    """Map an HTTP status code to the appropriate SandboxError subclass."""
    if status_code == 401:
        return AuthenticationError(message, status_code=status_code, body=body)
    if status_code == 404:
        return NotFoundError(message, status_code=status_code, body=body)
    if status_code == 429:
        return RateLimitError(message, status_code=status_code, body=body)
    if 500 <= status_code < 600:
        return ServerError(message, status_code=status_code, body=body)
    return SandboxError(message, status_code=status_code, body=body)
