# Generated by oagen. DO NOT EDIT.


from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field

from .enums import (
    FilterValuesResponsePhases,
    LogLineLevel,
    SandboxDomainSpecVisibility,
    StatusResponsePhase,
    VolumeFileEntryType,
    VolumeObjectSpecAccess,
    VolumePhase,
    VolumeSpecType,
    VolumeType,
)


class CountPoint(BaseModel):
    timestamp: str = Field(description="Start of the bucket.")
    count: int = Field(description="Sandboxes created within the bucket.")


class CountResponse(BaseModel):
    points: list[CountPoint] = Field(description="Created-sandbox counts per bucket, oldest first, gap-free.")
    granularity_ms: int = Field(description="Width of each bucket in milliseconds.")


class CreateResponse(BaseModel):
    id: str = Field(description="Sandbox ID")
    name: str = Field(description="Sandbox name (the id when no name was given)")
    volume_mounts: dict[str, str] | None = Field(default=None, description="Volumes the sandbox mounts, keyed by mount path")


class Error(BaseModel):
    error: str = Field(description="Error message")


class ExecRequest(BaseModel):
    command: list[str] = Field(description="Command and arguments to run in the sandbox")


class ExecResponse(BaseModel):
    stdout: str = Field(description="Captured standard output")
    stderr: str = Field(description="Captured standard error")
    exit_code: int = Field(description="Command exit code. Non-zero is a normal result, not an error.")


class ExecTarget(BaseModel):
    namespace: str = Field(description="Namespace of the sandbox pod")
    pod_name: str = Field(description="Name of the sandbox pod")
    container_name: str = Field(description="Container to target. For warm sandboxes this is the pod's placeholder container, which the node redirects to the injected workload.")


class FilterValuesResponse(BaseModel):
    tags: list[str] = Field(description="Distinct sandbox tags, formatted as key=value")
    images: list[str] = Field(description="Distinct sandbox images")
    phases: list[FilterValuesResponsePhases] = Field(description="Supported sandbox phases")


class HealthResponse(BaseModel):
    status: str = Field(description="Health status")


class ListResponse(BaseModel):
    sandboxes: list[StatusResponse] = Field(description="Matching sandboxes")
    pagination: Pagination
    filter_values: FilterValuesResponse | None = Field(default=None, description="Cluster-wide filter option values, included only when requested.")


class LogLine(BaseModel):
    timestamp: str = Field(description="When the log line was emitted")
    line: str = Field(description="Log line content")
    level: LogLineLevel = Field(description="Log severity level")
    exec_id: str = Field(description="ID of the exec that produced this line; empty when the line is the workload's own output")


class LogsResponse(BaseModel):
    sandbox_id: str = Field(description="Sandbox ID")
    logs: list[LogLine] = Field(description="Log lines")


class LookupResult(BaseModel):
    id: str = Field(description="The resolved resource id")


class MetricSummaryResponse(BaseModel):
    """p50/p90 CPU and memory usage over a lookback window with utilization against the sandbox's limits. Memory values include page cache, so they slightly overestimate resident memory."""
    model_config = ConfigDict(populate_by_name=True)

    window_seconds: int = Field(description="Lookback window the summary was computed over.")
    has_data: bool = Field(description="False when Prometheus returned no series for the sandbox's pod, which\nhappens for freshly-started sandboxes (Prometheus scrapes at ~1m) and\nfor pods shorter-lived than the [3m, 24h] window. When false, callers\nshould render \"no data yet\" rather than the zeroed metric fields.\n")
    cpu_cores_p_50: float = Field(alias="cpu_cores_p50", description="50th percentile CPU usage in cores.")
    cpu_cores_p_90: float = Field(alias="cpu_cores_p90", description="90th percentile CPU usage in cores.")
    cpu_limit_cores: float = Field(description="CPU limit configured on the sandbox pod, in cores. Zero when no limit is set.")
    cpu_util_p_50_pct: float = Field(alias="cpu_util_p50_pct", description="p50 CPU usage as a percentage of the CPU limit. Zero when no limit is set.")
    cpu_util_p_90_pct: float = Field(alias="cpu_util_p90_pct", description="p90 CPU usage as a percentage of the CPU limit. Zero when no limit is set.")
    mem_bytes_p_50: int = Field(alias="mem_bytes_p50", description="50th percentile memory usage in bytes. Includes page cache.")
    mem_bytes_p_90: int = Field(alias="mem_bytes_p90", description="90th percentile memory usage in bytes. Includes page cache.")
    mem_limit_bytes: int = Field(description="Memory limit configured on the sandbox pod, in bytes. Zero when no limit is set.")
    mem_util_p_50_pct: float = Field(alias="mem_util_p50_pct", description="p50 memory usage as a percentage of the memory limit. Zero when no limit is set.")
    mem_util_p_90_pct: float = Field(alias="mem_util_p90_pct", description="p90 memory usage as a percentage of the memory limit. Zero when no limit is set.")


class Pagination(BaseModel):
    current_page: int = Field(description="Current page number (1-based)")
    total_pages: int = Field(description="Total number of pages")
    has_next_page: bool = Field(description="Whether there are more items after this page")


class ReadinessResponse(BaseModel):
    status: str = Field(description="Readiness status")
    active_sandboxes: int = Field(description="Number of active sandboxes")


class SandboxDomainSpec(BaseModel):
    domain: str | None = Field(default=None, description="Fully qualified hostname for the sandbox, one label under the\ntarget ingress's domain. Unlike name it need not be unique, so\nsuccessive sandboxes can reuse one hostname (only one may be live\nat a time). Defaults to <name>.<ingress domain>, then\n<id>.<ingress domain>, when omitted.\n")
    visibility: SandboxDomainSpecVisibility | None = Field(default=None, description="Which sandbox ingress serves the domain when the cluster has both a\npublic and a private one. Omit to default to whichever is\nconfigured, public winning. Rejected when the sandbox exposes a\nport but the requested ingress is not configured on the cluster.\n")


class SandboxEgressSpec(BaseModel):
    allowed_destinations: list[str] = Field(description="Destinations the sandbox may reach; all other outbound traffic is\ndenied. An entry is a hostname (api.example.com), a wildcard\n(*.example.com) matching any host under that domain but not the\ndomain itself, an IP literal, a CIDR range (203.0.113.0/24), or the\ncluster-internal hostname of a Service on the sandbox's cluster\n(name.namespace.svc.cluster.local), which allows the Service's\nbacking pods as they change. Enforcement is transparent at the\nnetwork layer, so any protocol and client works without proxy\nconfiguration. An empty list denies all egress; omit egress entirely\nto leave the sandbox's internet access unrestricted.\n")


class SandboxMetricsPoint(BaseModel):
    timestamp_utc: str = Field(description="Timestamp for the data point, in UTC.")
    value: float = Field(description="Metric value at this timestamp.")


class SandboxMetricsResponse(BaseModel):
    """Time series for one sandbox metric over a range, shaped like the app metrics response so the dashboard reuses the same chart selectors."""
    results: list[SandboxMetricsResult] = Field(description="One entry per query; this endpoint returns a single entry.")


class SandboxMetricsResult(BaseModel):
    series: list[SandboxMetricsSeries] = Field(description="One entry per Prometheus series, normally the single sandbox pod.")


class SandboxMetricsSeries(BaseModel):
    labels: dict[str, str] | None = Field(default=None, description="Prometheus labels identifying the series.")
    unit: str | None = Field(default=None, description="Unit of the series values (e.g. cores, bytes, bytes/sec).")
    time_series: list[SandboxMetricsPoint] = Field(description="Data points in chronological order.")


class SandboxNetworkingSpec(BaseModel):
    port: int = Field(description="Port the workload listens on; the per-sandbox Service targets it on\nthe pod. Privileged ports (1-1023) are not allowed.\n")
    domains: list[SandboxDomainSpec] | None = Field(default=None, description="Domains the port is served on through a sandbox ingress. Omit to\nserve the port at the default hostname through the default ingress.\nCurrently only one entry is supported.\n")


class SandboxResourcesSpec(BaseModel):
    """CPU and memory for the sandbox, as Kubernetes quantities. An omitted
field keeps the cluster's default sandbox size for that resource. The
sandbox can use up to the given amount.
"""
    cpu: str | None = Field(default=None, description="CPU cores, e.g. \"2\", \"500m\".")
    memory: str | None = Field(default=None, description="Memory, e.g. \"2Gi\", \"512Mi\".")


class SandboxSpec(BaseModel):
    image: str = Field(description="Container image to run")
    name: str | None = Field(default=None, description="Sandbox name, unique within the cluster. Must be a valid DNS label\n(lowercase alphanumeric and dashes). Defaults to the sandbox's id\nwhen omitted.\n")
    tags: dict[str, str] | None = Field(default=None, description="Arbitrary key/value labels for identifying and filtering sandboxes")
    command: list[str] | None = Field(default=None, description="Override image entrypoint")
    args: list[str] | None = Field(default=None, description="Arguments passed to the command")
    env: dict[str, str] | None = Field(default=None, description="Environment variables to set in the sandbox, keyed by name")
    env_groups: list[str] | None = Field(default=None, description="Names of environment groups on the cluster whose variables are\ninjected into the sandbox, resolved to their latest version at create\ntime. On a key conflict a later group wins over an earlier one, and\nan explicit env entry wins over any group value.\n")
    volume_mounts: dict[str, str] | None = Field(default=None, description="Volumes to mount, keyed by the absolute mount path inside the\nsandbox; values are volume IDs.\n")
    networking: list[SandboxNetworkingSpec] | None = Field(default=None, description="Network exposure for the sandbox. Omit to expose nothing. Currently\nonly one entry is supported.\n")
    egress: SandboxEgressSpec | None = Field(default=None)
    resources: SandboxResourcesSpec | None = Field(default=None)
    ttl_seconds: int | None = Field(default=None, description="Maximum lifetime in seconds, counted from when the sandbox starts\nrunning (from creation while it waits to start). The sandbox is\nterminated once it elapses. Omit for no limit.\n")


class StatusResponse(BaseModel):
    id: str = Field(description="Sandbox ID")
    name: str = Field(description="Sandbox name (the id when no name was given)")
    image: str = Field(description="Image the sandbox runs")
    tags: dict[str, str] | None = Field(default=None, description="Tags the sandbox was created with")
    phase: StatusResponsePhase = Field(description="Current phase")
    exit_code: int | None = Field(default=None, description="Exit code if completed")
    created_at: str = Field(description="When the sandbox was created")
    started_at: str | None = Field(default=None, description="When the sandbox pod started running")
    finished_at: str | None = Field(default=None, description="When the sandbox reached a terminal phase (succeeded, failed, or terminated)")
    host: str = Field(description="Public hostname the sandbox is reachable at. Empty when the sandbox\nexposes no port or the cluster has no sandbox ingress configured.\n")
    volume_mounts: dict[str, str] | None = Field(default=None, description="Volumes the sandbox mounts, keyed by mount path")
    exec_target: ExecTarget | None = Field(default=None, description="Where a client addresses an interactive exec into the running sandbox. Absent until the sandbox has a pod.")


class Volume(BaseModel):
    id: str = Field(description="Volume ID, assigned when the volume is created. All volume\noperations address volumes by ID; the name is informational.\n")
    name: str = Field(description="Volume name")
    type: VolumeType = Field(description="Kind of volume. A disk volume is persistent file storage owned by\nthe volume; an object volume exposes a registered bucket.\n")
    object: VolumeObjectSpec | None = Field(default=None)
    path: str = Field(description="Subdirectory, relative to the shared sandbox volumes mount, where this\nvolume's data lives. An app that mounts the cluster's sandbox volumes\nreads this volume at <mount>/<path>. Empty for object volumes, which\nread straight from their bucket.\n")
    phase: VolumePhase = Field(description="Current lifecycle phase of the volume")
    attached_to: list[str] = Field(description="IDs of sandboxes the volume is attached to")
    created_at: str = Field(description="When the volume was created")


class VolumeFileEntry(BaseModel):
    name: str = Field(description="Entry name within its parent directory, without any path separator\n(e.g. model.bin). Entries nest, so a directory name is carried once\non the directory itself rather than repeated in the path of every\nentry beneath it. Reconstruct an entry's path relative to the volume\nroot by joining the names from the listing's path down to the entry.\n")
    type: VolumeFileEntryType = Field(description="Whether the entry is a regular file or a directory")
    size_bytes: int = Field(description="Size of the entry in bytes. Zero for directories.")
    modified_at: str | None = Field(default=None, description="When the entry was last modified. Always set on files; may be absent\non directories when the volume's storage keeps no directory\nmodification time.\n")
    truncated: bool | None = Field(default=None, description="Set on a directory entry whose contents the walk did not fully read:\nthe entry budget ran out before entering it, or the directory alone\nholds more entries than the budget. List the directory directly to\nread more of them. Never set on files.\n")
    entries: list[VolumeFileEntry] | None = Field(default=None, description="Entries directly inside this directory, directories before files and\neach group by name. Omitted on files, and on a directory whose\nentries the walk did not read (which carries truncated instead).\n")


class VolumeFileListResponse(BaseModel):
    path: str = Field(description="The walked directory, relative to the volume root")
    entries: list[VolumeFileEntry] = Field(description="Entries directly inside the walked directory, directories before\nfiles and each group by name. Entries nest, so everything the walk\nread below this level hangs off these entries rather than appearing\nhere as a flat path.\n")
    truncated: bool = Field(description="Whether the walk stopped at its entry budget before reading every\nentry. Directories left unread or partially read carry their own\ntruncated marker.\n")


class VolumeFileMoveRequest(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    from_: str = Field(alias="from", description="File or directory to move, relative to the volume root, with or\nwithout a leading slash. A directory moves with everything under it.\n")
    to: str = Field(description="Where to move it to, relative to the volume root, with or without a\nleading slash. This is the entry's full new path rather than the\ndirectory to place it in, so a move renames and relocates in one call.\nThe parent directory must already exist.\n")


class VolumeListResponse(BaseModel):
    volumes: list[Volume] = Field(description="All volumes in the cluster")


class VolumeObjectSpec(BaseModel):
    bucket: str = Field(description="Bucket the volume exposes. Must be registered on the cluster.\n")
    prefix: str | None = Field(default=None, description="Key prefix the volume is scoped to, without leading or trailing\nslashes. Sandboxes see only objects under the prefix, at paths\nrelative to it. Omit to expose the whole bucket.\n")
    access: VolumeObjectSpecAccess | None = Field(default=None, description="How sandboxes that attach the volume can use the bucket. read_only\nforbids all writes; write_only_new_files allows only new objects, with no\noverwrites or deletes of existing ones. Defaults to read_write. A\nbucket registered with read_only accepts only read_only volumes.\n")


class VolumeSpec(BaseModel):
    name: str | None = Field(default=None, description="Volume name, unique within the cluster. Must be a valid DNS label\n(lowercase alphanumeric and dashes). Defaults to the volume's id\nwhen omitted.\n")
    type: VolumeSpecType | None = Field(default=None, description="Kind of volume to create. A disk volume is persistent file storage\nowned by the volume; an object volume exposes a bucket registered\non the cluster. Defaults to disk when omitted.\n")
    object: VolumeObjectSpec | None = Field(default=None)


__all__ = ["CountPoint", "CountResponse", "CreateResponse", "Error", "ExecRequest", "ExecResponse", "ExecTarget", "FilterValuesResponse", "HealthResponse", "ListResponse", "LogLine", "LogsResponse", "LookupResult", "MetricSummaryResponse", "Pagination", "ReadinessResponse", "SandboxDomainSpec", "SandboxEgressSpec", "SandboxMetricsPoint", "SandboxMetricsResponse", "SandboxMetricsResult", "SandboxMetricsSeries", "SandboxNetworkingSpec", "SandboxResourcesSpec", "SandboxSpec", "StatusResponse", "Volume", "VolumeFileEntry", "VolumeFileListResponse", "VolumeFileMoveRequest", "VolumeListResponse", "VolumeObjectSpec", "VolumeSpec"]
