# Generated by oagen. DO NOT EDIT.


from __future__ import annotations

from pydantic import BaseModel, Field

from .enums import (
    FilterValuesResponsePhases,
    LogLineLevel,
    SandboxDomainSpecVisibility,
    StatusResponsePhase,
    VolumePhase,
)


class CountPoint(BaseModel):
    timestamp: str = Field(description="Start of the bucket.")
    count: int = Field(description="Sandboxes created within the bucket.")


class CountResponse(BaseModel):
    points: list[CountPoint] = Field(description="Created-sandbox counts per bucket, oldest first, gap-free.")
    granularity_ms: int = Field(description="Width of each bucket in milliseconds.")


class CreateResponse(BaseModel):
    id: str = Field(description="Sandbox ID")
    name: str = Field(description="Sandbox name (the id when no name was given)")
    volume_mounts: dict[str, str] | None = Field(default=None, description="Volumes the sandbox mounts, keyed by mount path")


class Error(BaseModel):
    error: str = Field(description="Error message")


class ExecRequest(BaseModel):
    command: list[str] = Field(description="Command and arguments to run in the sandbox")


class ExecResponse(BaseModel):
    stdout: str = Field(description="Captured standard output")
    stderr: str = Field(description="Captured standard error")
    exit_code: int = Field(description="Command exit code. Non-zero is a normal result, not an error.")


class ExecTarget(BaseModel):
    namespace: str = Field(description="Namespace of the sandbox pod")
    pod_name: str = Field(description="Name of the sandbox pod")
    container_name: str = Field(description="Container to target. For warm sandboxes this is the pod's placeholder container, which the node redirects to the injected workload.")


class FilterValuesResponse(BaseModel):
    tags: list[str] = Field(description="Distinct sandbox tags, formatted as key=value")
    images: list[str] = Field(description="Distinct sandbox images")
    phases: list[FilterValuesResponsePhases] = Field(description="Supported sandbox phases")


class HealthResponse(BaseModel):
    status: str = Field(description="Health status")


class ListResponse(BaseModel):
    sandboxes: list[StatusResponse] = Field(description="Matching sandboxes")
    pagination: Pagination
    filter_values: FilterValuesResponse | None = Field(default=None, description="Cluster-wide filter option values, included only when requested.")


class LogLine(BaseModel):
    timestamp: str = Field(description="When the log line was emitted")
    line: str = Field(description="Log line content")
    level: LogLineLevel = Field(description="Log severity level")
    exec_id: str = Field(description="ID of the exec that produced this line; empty when the line is the workload's own output")


class LogsResponse(BaseModel):
    sandbox_id: str = Field(description="Sandbox ID")
    logs: list[LogLine] = Field(description="Log lines")


class LookupResult(BaseModel):
    id: str = Field(description="The resolved resource id")


class Pagination(BaseModel):
    current_page: int = Field(description="Current page number (1-based)")
    total_pages: int = Field(description="Total number of pages")
    has_next_page: bool = Field(description="Whether there are more items after this page")


class ReadinessResponse(BaseModel):
    status: str = Field(description="Readiness status")
    active_sandboxes: int = Field(description="Number of active sandboxes")


class SandboxDomainSpec(BaseModel):
    domain: str | None = Field(default=None, description="Fully qualified hostname for the sandbox, one label under the\ntarget ingress's domain. Unlike name it need not be unique, so\nsuccessive sandboxes can reuse one hostname (only one may be live\nat a time). Defaults to <name>.<ingress domain>, then\n<id>.<ingress domain>, when omitted.\n")
    visibility: SandboxDomainSpecVisibility | None = Field(default=None, description="Which sandbox ingress serves the domain when the cluster has both a\npublic and a private one. Omit to default to whichever is\nconfigured, public winning. Rejected when the sandbox exposes a\nport but the requested ingress is not configured on the cluster.\n")


class SandboxNetworkingSpec(BaseModel):
    port: int = Field(description="Port the workload listens on; the per-sandbox Service targets it on\nthe pod. Privileged ports (1-1023) are not allowed.\n")
    domains: list[SandboxDomainSpec] | None = Field(default=None, description="Domains the port is served on through a sandbox ingress. Omit to\nserve the port at the default hostname through the default ingress.\nCurrently only one entry is supported.\n")


class SandboxSpec(BaseModel):
    image: str = Field(description="Container image to run")
    name: str | None = Field(default=None, description="Sandbox name, unique within the cluster. Must be a valid DNS label\n(lowercase alphanumeric and dashes). Defaults to the sandbox's id\nwhen omitted.\n")
    tags: dict[str, str] | None = Field(default=None, description="Arbitrary key/value labels for identifying and filtering sandboxes")
    command: list[str] | None = Field(default=None, description="Override image entrypoint")
    args: list[str] | None = Field(default=None, description="Arguments passed to the command")
    env: dict[str, str] | None = Field(default=None, description="Environment variables to set in the sandbox, keyed by name")
    volume_mounts: dict[str, str] | None = Field(default=None, description="Volumes to mount, keyed by the absolute mount path inside the\nsandbox; values are volume IDs.\n")
    networking: list[SandboxNetworkingSpec] | None = Field(default=None, description="Network exposure for the sandbox. Omit to expose nothing. Currently\nonly one entry is supported.\n")


class StatusResponse(BaseModel):
    id: str = Field(description="Sandbox ID")
    name: str = Field(description="Sandbox name (the id when no name was given)")
    image: str = Field(description="Image the sandbox runs")
    tags: dict[str, str] | None = Field(default=None, description="Tags the sandbox was created with")
    phase: StatusResponsePhase = Field(description="Current phase")
    exit_code: int | None = Field(default=None, description="Exit code if completed")
    created_at: str = Field(description="When the sandbox was created")
    started_at: str | None = Field(default=None, description="When the sandbox pod started running")
    host: str = Field(description="Public hostname the sandbox is reachable at. Empty when the sandbox\nexposes no port or the cluster has no sandbox ingress configured.\n")
    volume_mounts: dict[str, str] | None = Field(default=None, description="Volumes the sandbox mounts, keyed by mount path")
    exec_target: ExecTarget | None = Field(default=None, description="Where a client addresses an interactive exec into the running sandbox. Absent until the sandbox has a pod.")


class Volume(BaseModel):
    id: str = Field(description="Volume ID, assigned when the volume is created. All volume\noperations address volumes by ID; the name is informational.\n")
    name: str = Field(description="Volume name")
    phase: VolumePhase = Field(description="Current lifecycle phase of the volume")
    attached_to: list[str] = Field(description="IDs of sandboxes the volume is attached to")
    created_at: str = Field(description="When the volume was created")


class VolumeListResponse(BaseModel):
    volumes: list[Volume] = Field(description="All volumes in the cluster")


class VolumeSpec(BaseModel):
    name: str | None = Field(default=None, description="Volume name, unique within the cluster. Must be a valid DNS label\n(lowercase alphanumeric and dashes). Defaults to the volume's id\nwhen omitted.\n")


__all__ = ["CountPoint", "CountResponse", "CreateResponse", "Error", "ExecRequest", "ExecResponse", "ExecTarget", "FilterValuesResponse", "HealthResponse", "ListResponse", "LogLine", "LogsResponse", "LookupResult", "Pagination", "ReadinessResponse", "SandboxDomainSpec", "SandboxNetworkingSpec", "SandboxSpec", "StatusResponse", "Volume", "VolumeListResponse", "VolumeSpec"]
