# Generated by oagen. DO NOT EDIT.


from __future__ import annotations

from enum import Enum


class FilterValuesResponsePhases(str, Enum):
    QUEUED = "queued"
    CREATING = "creating"
    RUNNING = "running"
    SUCCEEDED = "succeeded"
    FAILED = "failed"
    TERMINATED = "terminated"


class LogLineLevel(str, Enum):
    ERROR = "error"
    WARNING = "warning"
    INFO = "info"


class SandboxDomainSpecVisibility(str, Enum):
    PUBLIC = "public"
    PRIVATE = "private"


class SandboxesPhase(str, Enum):
    QUEUED = "queued"
    CREATING = "creating"
    RUNNING = "running"
    SUCCEEDED = "succeeded"
    FAILED = "failed"
    TERMINATED = "terminated"


class SandboxMetric(str, Enum):
    CPU_USAGE = "cpu_usage"
    CPU_RESERVED = "cpu_reserved"
    MEMORY_USAGE = "memory_usage"
    MEMORY_RESERVED = "memory_reserved"
    NETWORK_RX = "network_rx"
    NETWORK_TX = "network_tx"


class StatusResponsePhase(str, Enum):
    QUEUED = "queued"
    CREATING = "creating"
    RUNNING = "running"
    SUCCEEDED = "succeeded"
    FAILED = "failed"
    TERMINATED = "terminated"


class VolumeFileEntryType(str, Enum):
    FILE = "file"
    DIRECTORY = "directory"


class VolumeObjectSpecAccess(str, Enum):
    READ_WRITE = "read_write"
    READ_ONLY = "read_only"
    WRITE_ONLY_NEW_FILES = "write_only_new_files"


class VolumePhase(str, Enum):
    PENDING = "pending"
    READY = "ready"
    FAILED = "failed"


class VolumeSpecType(str, Enum):
    DISK = "disk"
    OBJECT = "object"


class VolumeType(str, Enum):
    DISK = "disk"
    OBJECT = "object"


__all__ = ["FilterValuesResponsePhases", "LogLineLevel", "SandboxDomainSpecVisibility", "SandboxesPhase", "SandboxMetric", "StatusResponsePhase", "VolumeFileEntryType", "VolumeObjectSpecAccess", "VolumePhase", "VolumeSpecType", "VolumeType"]
