# Generated by oagen. DO NOT EDIT.


from __future__ import annotations

from enum import Enum


class FilterValuesResponsePhases(str, Enum):
    QUEUED = "queued"
    CREATING = "creating"
    RUNNING = "running"
    SUCCEEDED = "succeeded"
    FAILED = "failed"
    TERMINATED = "terminated"


class LogLineLevel(str, Enum):
    ERROR = "error"
    WARNING = "warning"
    INFO = "info"


class SandboxDomainSpecVisibility(str, Enum):
    PUBLIC = "public"
    PRIVATE = "private"


class SandboxesPhase(str, Enum):
    QUEUED = "queued"
    CREATING = "creating"
    RUNNING = "running"
    SUCCEEDED = "succeeded"
    FAILED = "failed"
    TERMINATED = "terminated"


class StatusResponsePhase(str, Enum):
    QUEUED = "queued"
    CREATING = "creating"
    RUNNING = "running"
    SUCCEEDED = "succeeded"
    FAILED = "failed"
    TERMINATED = "terminated"


class VolumePhase(str, Enum):
    PENDING = "pending"
    READY = "ready"
    FAILED = "failed"


__all__ = ["FilterValuesResponsePhases", "LogLineLevel", "SandboxDomainSpecVisibility", "SandboxesPhase", "StatusResponsePhase", "VolumePhase"]
