# Generated by oagen. DO NOT EDIT.


from __future__ import annotations

from porter_sandbox._models import HealthResponse
from porter_sandbox.resources.healthz import AsyncHealthz as AsyncHealthzResource
from porter_sandbox.resources.healthz import Healthz as HealthzResource


class Healthz:
    """User-facing healthz namespace."""

    def __init__(self, resource: HealthzResource) -> None:
        self._resource = resource

    @property
    def raw(self) -> HealthzResource:
        """Direct access to the generated low-level healthz resource."""
        return self._resource

    def health_check(self) -> HealthResponse:
        return self._resource.health_check()


class AsyncHealthz:
    """User-facing healthz namespace."""

    def __init__(self, resource: AsyncHealthzResource) -> None:
        self._resource = resource

    @property
    def raw(self) -> AsyncHealthzResource:
        """Direct access to the generated low-level healthz resource."""
        return self._resource

    async def health_check(self) -> HealthResponse:
        return await self._resource.health_check()
