# Generated by oagen. DO NOT EDIT.


from __future__ import annotations

from porter_sandbox._client import AsyncPorterSandboxApiClient, PorterSandboxApiClient
from porter_sandbox.healthz import AsyncHealthz, Healthz
from porter_sandbox.readyz import AsyncReadyz, Readyz
from porter_sandbox.sandboxes import AsyncSandboxes, Sandboxes
from porter_sandbox.volumes import AsyncVolumes, Volumes


class Porter:
    """Top-level Porter client."""

    def __init__(
        self,
        *,
        api_key: str | None = None,
        base_url: str | None = None,
        timeout: float | None = None,
    ) -> None:
        self._client = PorterSandboxApiClient(
            api_key=api_key,
            base_url=base_url,
            timeout=timeout,
        )
        self.healthz: Healthz = Healthz(self._client.healthz)
        self.readyz: Readyz = Readyz(self._client.readyz)
        self.sandboxes: Sandboxes = Sandboxes(self._client.sandboxes)
        self.volumes: Volumes = Volumes(self._client.volumes)

    @property
    def raw(self) -> PorterSandboxApiClient:
        """Direct access to the generated low-level API client."""
        return self._client

    def __enter__(self) -> Porter:
        self._client.__enter__()
        return self

    def __exit__(self, *exc: object) -> None:
        self._client.__exit__(*exc)

    def close(self) -> None:
        self._client.close()


class AsyncPorter:
    """Top-level async Porter client."""

    def __init__(
        self,
        *,
        api_key: str | None = None,
        base_url: str | None = None,
        timeout: float | None = None,
    ) -> None:
        self._client = AsyncPorterSandboxApiClient(
            api_key=api_key,
            base_url=base_url,
            timeout=timeout,
        )
        self.healthz: AsyncHealthz = AsyncHealthz(self._client.healthz)
        self.readyz: AsyncReadyz = AsyncReadyz(self._client.readyz)
        self.sandboxes: AsyncSandboxes = AsyncSandboxes(self._client.sandboxes)
        self.volumes: AsyncVolumes = AsyncVolumes(self._client.volumes)

    @property
    def raw(self) -> AsyncPorterSandboxApiClient:
        """Direct access to the generated low-level API client."""
        return self._client

    async def __aenter__(self) -> AsyncPorter:
        await self._client.__aenter__()
        return self

    async def __aexit__(self, *exc: object) -> None:
        await self._client.__aexit__(*exc)

    async def aclose(self) -> None:
        await self._client.aclose()
