# Generated by oagen. DO NOT EDIT.


from __future__ import annotations

from porter_sandbox._models import ReadinessResponse
from porter_sandbox.resources.readyz import AsyncReadyz as AsyncReadyzResource
from porter_sandbox.resources.readyz import Readyz as ReadyzResource


class Readyz:
    """User-facing readyz namespace."""

    def __init__(self, resource: ReadyzResource) -> None:
        self._resource = resource

    @property
    def raw(self) -> ReadyzResource:
        """Direct access to the generated low-level readyz resource."""
        return self._resource

    def readiness_check(self) -> ReadinessResponse:
        return self._resource.readiness_check()


class AsyncReadyz:
    """User-facing readyz namespace."""

    def __init__(self, resource: AsyncReadyzResource) -> None:
        self._resource = resource

    @property
    def raw(self) -> AsyncReadyzResource:
        """Direct access to the generated low-level readyz resource."""
        return self._resource

    async def readiness_check(self) -> ReadinessResponse:
        return await self._resource.readiness_check()
