# Generated by oagen. DO NOT EDIT.


from __future__ import annotations

import builtins

from porter_sandbox._models import SandboxNetworkingSpec, SandboxSpec
from porter_sandbox.enums import SandboxesPhase
from porter_sandbox.resources.sandboxes import AsyncSandboxes as AsyncSandboxesResource
from porter_sandbox.resources.sandboxes import Sandboxes as SandboxesResource
from porter_sandbox.sandbox import AsyncSandbox, Sandbox


class Sandboxes:
    """User-facing sandbox namespace under `Porter`."""

    def __init__(self, resource: SandboxesResource) -> None:
        self._resource = resource

    @property
    def raw(self) -> SandboxesResource:
        """Direct access to the generated low-level sandbox resource."""
        return self._resource

    def create(
        self,
        image: str,
        *,
        name: str | None = None,
        tags: dict[str, str] | None = None,
        command: list[str] | None = None,
        args: list[str] | None = None,
        env: dict[str, str] | None = None,
        volume_mounts: dict[str, str] | None = None,
        networking: list[SandboxNetworkingSpec] | None = None,
    ) -> Sandbox:
        spec = SandboxSpec(
            image=image,
            name=name,
            tags=tags,
            command=command,
            args=args,
            env=env,
            volume_mounts=volume_mounts,
            networking=networking,
        )
        created = self._resource.create_sandbox(body=spec)
        return Sandbox(id=created.id, resource=self._resource)

    def get(self, name: str) -> Sandbox:
        ref = self._resource.lookup_sandbox(name=name)
        status = self._resource.get_sandbox(id=ref.id)
        return Sandbox(id=ref.id, resource=self._resource, status=status)

    def list(
        self,
        *,
        start_time: str | None = None,
        end_time: str | None = None,
        search: str | None = None,
        tags: dict[str, str] | None = None,
        phase: list[SandboxesPhase] | None = None,
        image: str | None = None,
        include_filter_values: bool | None = None,
        page: int | None = None,
    ) -> builtins.list[Sandbox]:
        tag_filter = [f"{k}={v}" for k, v in tags.items()] if tags else None
        response = self._resource.list_sandboxes(start_time=start_time, end_time=end_time, search=search, tag=tag_filter, phase=phase, image=image, include_filter_values=include_filter_values, page=page)
        return [Sandbox(id=s.id, resource=self._resource, status=s) for s in response.sandboxes]


class AsyncSandboxes:
    """User-facing async sandbox namespace under `AsyncPorter`."""

    def __init__(self, resource: AsyncSandboxesResource) -> None:
        self._resource = resource

    @property
    def raw(self) -> AsyncSandboxesResource:
        """Direct access to the generated low-level async sandbox resource."""
        return self._resource

    async def create(
        self,
        image: str,
        *,
        name: str | None = None,
        tags: dict[str, str] | None = None,
        command: list[str] | None = None,
        args: list[str] | None = None,
        env: dict[str, str] | None = None,
        volume_mounts: dict[str, str] | None = None,
        networking: list[SandboxNetworkingSpec] | None = None,
    ) -> AsyncSandbox:
        spec = SandboxSpec(
            image=image,
            name=name,
            tags=tags,
            command=command,
            args=args,
            env=env,
            volume_mounts=volume_mounts,
            networking=networking,
        )
        created = await self._resource.create_sandbox(body=spec)
        return AsyncSandbox(id=created.id, resource=self._resource)

    async def get(self, name: str) -> AsyncSandbox:
        ref = await self._resource.lookup_sandbox(name=name)
        status = await self._resource.get_sandbox(id=ref.id)
        return AsyncSandbox(id=ref.id, resource=self._resource, status=status)

    async def list(
        self,
        *,
        start_time: str | None = None,
        end_time: str | None = None,
        search: str | None = None,
        tags: dict[str, str] | None = None,
        phase: list[SandboxesPhase] | None = None,
        image: str | None = None,
        include_filter_values: bool | None = None,
        page: int | None = None,
    ) -> builtins.list[AsyncSandbox]:
        tag_filter = [f"{k}={v}" for k, v in tags.items()] if tags else None
        response = await self._resource.list_sandboxes(start_time=start_time, end_time=end_time, search=search, tag=tag_filter, phase=phase, image=image, include_filter_values=include_filter_values, page=page)
        return [AsyncSandbox(id=s.id, resource=self._resource, status=s) for s in response.sandboxes]
