# Generated by oagen. DO NOT EDIT.


from __future__ import annotations

from porter_sandbox._models import Snapshot, SnapshotListResponse, SnapshotSpec
from porter_sandbox.resources.snapshots import AsyncSnapshots as AsyncSnapshotsResource
from porter_sandbox.resources.snapshots import Snapshots as SnapshotsResource


class Snapshots:
    """User-facing snapshots namespace."""

    def __init__(self, resource: SnapshotsResource) -> None:
        self._resource = resource

    @property
    def raw(self) -> SnapshotsResource:
        """Direct access to the generated low-level snapshots resource."""
        return self._resource

    def create(self, id: str, body: SnapshotSpec) -> Snapshot:
        return self._resource.create_snapshot(id=id, body=body)

    def list(self, sandbox_id: str | None = None) -> SnapshotListResponse:
        return self._resource.list_snapshots(sandbox_id=sandbox_id)

    def delete(self, id: str) -> None:
        self._resource.delete_snapshot(id=id)
        return None


class AsyncSnapshots:
    """User-facing snapshots namespace."""

    def __init__(self, resource: AsyncSnapshotsResource) -> None:
        self._resource = resource

    @property
    def raw(self) -> AsyncSnapshotsResource:
        """Direct access to the generated low-level snapshots resource."""
        return self._resource

    async def create(self, id: str, body: SnapshotSpec) -> Snapshot:
        return await self._resource.create_snapshot(id=id, body=body)

    async def list(self, sandbox_id: str | None = None) -> SnapshotListResponse:
        return await self._resource.list_snapshots(sandbox_id=sandbox_id)

    async def delete(self, id: str) -> None:
        await self._resource.delete_snapshot(id=id)
        return None
