# Generated by oagen. DO NOT EDIT.


from __future__ import annotations

from porter_sandbox._models import Volume, VolumeListResponse, VolumeSpec
from porter_sandbox.resources.volumes import AsyncVolumes as AsyncVolumesResource
from porter_sandbox.resources.volumes import Volumes as VolumesResource


class Volumes:
    """User-facing volumes namespace under `Porter`."""

    def __init__(self, resource: VolumesResource) -> None:
        self._resource = resource

    @property
    def raw(self) -> VolumesResource:
        """Direct access to the generated low-level volumes resource."""
        return self._resource

    def create(
        self,
        *,
        name: str | None = None,
    ) -> Volume:
        spec = VolumeSpec(
            name=name,
        )
        return self._resource.create_volume(body=spec)

    def list(self) -> VolumeListResponse:
        return self._resource.list_volumes()

    def get(self, name: str) -> Volume:
        ref = self._resource.lookup_volume(name=name)
        return self._resource.get_volume(id=ref.id)

    def delete(self, name: str) -> None:
        ref = self._resource.lookup_volume(name=name)
        self._resource.delete_volume(id=ref.id)
        return None


class AsyncVolumes:
    """User-facing async volumes namespace under `AsyncPorter`."""

    def __init__(self, resource: AsyncVolumesResource) -> None:
        self._resource = resource

    @property
    def raw(self) -> AsyncVolumesResource:
        """Direct access to the generated low-level async volumes resource."""
        return self._resource

    async def create(
        self,
        *,
        name: str | None = None,
    ) -> Volume:
        spec = VolumeSpec(
            name=name,
        )
        return await self._resource.create_volume(body=spec)

    async def list(self) -> VolumeListResponse:
        return await self._resource.list_volumes()

    async def get(self, name: str) -> Volume:
        ref = await self._resource.lookup_volume(name=name)
        return await self._resource.get_volume(id=ref.id)

    async def delete(self, name: str) -> None:
        ref = await self._resource.lookup_volume(name=name)
        await self._resource.delete_volume(id=ref.id)
        return None
