# Generated by oagen. DO NOT EDIT.


from __future__ import annotations

import builtins

from porter_sandbox._models import VolumeSpec
from porter_sandbox.resources.volumes import AsyncVolumes as AsyncVolumesResource
from porter_sandbox.resources.volumes import Volumes as VolumesResource
from porter_sandbox.volume import AsyncVolume, Volume


class Volumes:
    """User-facing volumes namespace under `Porter`."""

    def __init__(self, resource: VolumesResource) -> None:
        self._resource = resource

    @property
    def raw(self) -> VolumesResource:
        """Direct access to the generated low-level volumes resource."""
        return self._resource

    def create(
        self,
        *,
        name: str | None = None,
    ) -> Volume:
        spec = VolumeSpec(
            name=name,
        )
        record = self._resource.create_volume(body=spec)
        return Volume(record=record, resource=self._resource)

    def list(self) -> builtins.list[Volume]:
        response = self._resource.list_volumes()
        return [Volume(record=r, resource=self._resource) for r in response.volumes]

    def get(self, name: str) -> Volume:
        ref = self._resource.lookup_volume(name=name)
        record = self._resource.get_volume(id=ref.id)
        return Volume(record=record, resource=self._resource)

    def delete(self, name: str) -> None:
        ref = self._resource.lookup_volume(name=name)
        self._resource.delete_volume(id=ref.id)
        return None


class AsyncVolumes:
    """User-facing async volumes namespace under `AsyncPorter`."""

    def __init__(self, resource: AsyncVolumesResource) -> None:
        self._resource = resource

    @property
    def raw(self) -> AsyncVolumesResource:
        """Direct access to the generated low-level async volumes resource."""
        return self._resource

    async def create(
        self,
        *,
        name: str | None = None,
    ) -> AsyncVolume:
        spec = VolumeSpec(
            name=name,
        )
        record = await self._resource.create_volume(body=spec)
        return AsyncVolume(record=record, resource=self._resource)

    async def list(self) -> builtins.list[AsyncVolume]:
        response = await self._resource.list_volumes()
        return [AsyncVolume(record=r, resource=self._resource) for r in response.volumes]

    async def get(self, name: str) -> AsyncVolume:
        ref = await self._resource.lookup_volume(name=name)
        record = await self._resource.get_volume(id=ref.id)
        return AsyncVolume(record=record, resource=self._resource)

    async def delete(self, name: str) -> None:
        ref = await self._resource.lookup_volume(name=name)
        await self._resource.delete_volume(id=ref.id)
        return None
