# Generated by oagen. DO NOT EDIT.


from __future__ import annotations

import builtins
from collections.abc import AsyncIterator, Iterator
from datetime import datetime

from porter_sandbox._models import Volume as VolumeRecord
from porter_sandbox._models import VolumeFileEntry
from porter_sandbox.enums import VolumeFileEntryType, VolumePhase
from porter_sandbox.resources.volumes import AsyncVolumes as AsyncVolumesResource
from porter_sandbox.resources.volumes import Volumes as VolumesResource

# How much of a file one request of `stream` reads. Files are read through
# ranged requests, so this bounds how many bytes a caller holds at once.
DEFAULT_CHUNK_BYTES = 8 * 1024 * 1024


def _normalize_path(path: str) -> str:
    """Take a volume path with or without a leading slash, return the '/'-rooted form the API echoes back."""
    trimmed = path.strip("/")
    return f"/{trimmed}" if trimmed else "/"


def _join_path(parent: str, name: str) -> str:
    return f"/{name}" if parent == "/" else f"{parent}/{name}"


def _byte_range_header(offset: int, length: int | None) -> str:
    return f"bytes={offset}-" if length is None else f"bytes={offset}-{offset + length - 1}"


def _parse_timestamp(value: str | None) -> datetime | None:
    if not value:
        return None
    # The API sends RFC 3339, where fromisoformat only learned to read the 'Z'
    # suffix in Python 3.11.
    return datetime.fromisoformat(value.replace("Z", "+00:00"))


class VolumeFile:
    """A file or directory inside a volume."""

    def __init__(self, entry: VolumeFileEntry, parent_path: str) -> None:
        #: Entry name within its parent directory, without any path separator.
        self.name = entry.name
        #: Path relative to the volume root, e.g. "/models/config.json".
        self.path = _join_path(parent_path, entry.name)
        self.type: VolumeFileEntryType = entry.type
        self.size_bytes = entry.size_bytes
        self.modified_at = _parse_timestamp(entry.modified_at)
        #: Set on a directory the server's listing walk did not fully read — it
        #: holds more entries than one listing covers. `iterdir` reads these
        #: directly; `listdir` leaves them for the caller to list.
        self.truncated = entry.truncated or False

    @property
    def is_directory(self) -> bool:
        return self.type == VolumeFileEntryType.DIRECTORY

    @property
    def is_file(self) -> bool:
        return self.type == VolumeFileEntryType.FILE

    def __repr__(self) -> str:
        return f"VolumeFile(path={self.path!r}, type={self.type!r}, size_bytes={self.size_bytes})"


class Volume:
    """Ergonomic handle for a single volume (sync).

    Constructed by `Porter().volumes`. Holds a back-reference to the generated
    volume resource so file reads and lifecycle calls do not need a client to be
    re-passed.

    For async usage, see `AsyncVolume` (same surface, async methods).
    """

    def __init__(self, *, record: VolumeRecord, resource: VolumesResource) -> None:
        self._record = record
        self._volumes = resource

    @property
    def id(self) -> str:
        return self._record.id

    @property
    def name(self) -> str:
        return self._record.name

    @property
    def phase(self) -> VolumePhase:
        return self._record.phase

    @property
    def path(self) -> str:
        """Subdirectory, relative to the shared sandbox volumes mount, where this
        volume's data lives. An app that mounts the cluster's sandbox volumes
        reads this volume at `<mount>/<path>`.
        """
        return self._record.path

    @property
    def attached_to(self) -> builtins.list[str]:
        """IDs of the sandboxes the volume is attached to."""
        return self._record.attached_to

    @property
    def created_at(self) -> datetime | None:
        return _parse_timestamp(self._record.created_at)

    def refresh(self) -> VolumeRecord:
        """Refetch and cache the volume record."""
        self._record = self._volumes.get_volume(id=self.id)
        return self._record

    def delete(self) -> None:
        """Delete the volume. Fails while it is attached to a sandbox."""
        self._volumes.delete_volume(id=self.id)

    def listdir(self, path: str = "/") -> builtins.list[VolumeFile]:
        """The entries directly inside `path`, directories first and each group by name."""
        parent = _normalize_path(path)
        listing = self._volumes.list_volume_files(id=self.id, path=parent)
        return [VolumeFile(entry, parent) for entry in listing.entries]

    def iterdir(self, path: str = "/") -> Iterator[VolumeFile]:
        """Every entry under `path`, depth-first.

        One listing covers a bounded number of entries, so directories it left
        unread are listed as the walk reaches them — a large tree costs more
        than one request.
        """
        parent = _normalize_path(path)
        listing = self._volumes.list_volume_files(id=self.id, path=parent)
        yield from self._walk_entries(parent, listing.entries, follow_truncated=True)

    def search(self, query: str, *, path: str = "/") -> builtins.list[VolumeFile]:
        """Entries under `path` whose name contains `query`, case-insensitively.

        The search runs inside one listing walk, so a tree too large for a
        single listing is searched as far as that walk reached.
        """
        parent = _normalize_path(path)
        listing = self._volumes.list_volume_files(id=self.id, path=parent, search=query)
        needle = query.lower()
        # The API prunes the tree to matches plus the directories holding them;
        # keep only the entries that match so callers get the hits alone.
        return [
            file
            for file in self._walk_entries(parent, listing.entries, follow_truncated=False)
            if needle in file.name.lower()
        ]

    def read_file(self, path: str, *, offset: int | None = None, length: int | None = None) -> bytes:
        """Read a file's bytes. `offset` and `length` read a slice of it instead of the whole file."""
        ranged = offset is not None or length is not None
        content = self._volumes.read_volume_file(
            id=self.id,
            path=_normalize_path(path),
            range=_byte_range_header(offset or 0, length) if ranged else None,
        )
        return content.data

    def read_text(
        self,
        path: str,
        *,
        offset: int | None = None,
        length: int | None = None,
        encoding: str = "utf-8",
    ) -> str:
        """Read a file as text."""
        return self.read_file(path, offset=offset, length=length).decode(encoding)

    def stream(self, path: str, *, chunk_size: int = DEFAULT_CHUNK_BYTES) -> Iterator[bytes]:
        """Read a file in chunks, so a large one never lands in memory whole.

        Each chunk is its own ranged request.
        """
        file_path = _normalize_path(path)
        offset = 0

        while True:
            content = self._volumes.read_volume_file(
                id=self.id,
                path=file_path,
                range=_byte_range_header(offset, chunk_size),
            )
            if content.data:
                yield content.data

            # An empty file comes back whole, with no Content-Range to page from.
            if content.content_range is None:
                return

            offset = content.content_range.end + 1
            if offset >= content.content_range.size:
                return

    # Depth-first over a listing's nested entries. `follow_truncated` lists the
    # directories the server's walk left unread, which `iterdir` wants and
    # `search` does not: listing one of those directly would drop the search
    # term and pull in everything under it.
    def _walk_entries(
        self,
        parent: str,
        entries: builtins.list[VolumeFileEntry],
        *,
        follow_truncated: bool,
    ) -> Iterator[VolumeFile]:
        for entry in entries:
            file = VolumeFile(entry, parent)
            yield file
            if not file.is_directory:
                continue
            if entry.entries is not None:
                yield from self._walk_entries(
                    file.path, entry.entries, follow_truncated=follow_truncated
                )
            elif file.truncated and follow_truncated:
                yield from self.iterdir(file.path)


class AsyncVolume:
    """Ergonomic handle for a single volume (async).

    Same surface as `Volume`, but every method is awaitable and the walks are
    async iterators.
    """

    def __init__(self, *, record: VolumeRecord, resource: AsyncVolumesResource) -> None:
        self._record = record
        self._volumes = resource

    @property
    def id(self) -> str:
        return self._record.id

    @property
    def name(self) -> str:
        return self._record.name

    @property
    def phase(self) -> VolumePhase:
        return self._record.phase

    @property
    def path(self) -> str:
        """Subdirectory, relative to the shared sandbox volumes mount, where this
        volume's data lives. An app that mounts the cluster's sandbox volumes
        reads this volume at `<mount>/<path>`.
        """
        return self._record.path

    @property
    def attached_to(self) -> builtins.list[str]:
        """IDs of the sandboxes the volume is attached to."""
        return self._record.attached_to

    @property
    def created_at(self) -> datetime | None:
        return _parse_timestamp(self._record.created_at)

    async def refresh(self) -> VolumeRecord:
        """Refetch and cache the volume record."""
        self._record = await self._volumes.get_volume(id=self.id)
        return self._record

    async def delete(self) -> None:
        """Delete the volume. Fails while it is attached to a sandbox."""
        await self._volumes.delete_volume(id=self.id)

    async def listdir(self, path: str = "/") -> builtins.list[VolumeFile]:
        """The entries directly inside `path`, directories first and each group by name."""
        parent = _normalize_path(path)
        listing = await self._volumes.list_volume_files(id=self.id, path=parent)
        return [VolumeFile(entry, parent) for entry in listing.entries]

    async def iterdir(self, path: str = "/") -> AsyncIterator[VolumeFile]:
        """Every entry under `path`, depth-first.

        One listing covers a bounded number of entries, so directories it left
        unread are listed as the walk reaches them — a large tree costs more
        than one request.
        """
        parent = _normalize_path(path)
        listing = await self._volumes.list_volume_files(id=self.id, path=parent)
        async for file in self._walk_entries(parent, listing.entries, follow_truncated=True):
            yield file

    async def search(self, query: str, *, path: str = "/") -> builtins.list[VolumeFile]:
        """Entries under `path` whose name contains `query`, case-insensitively.

        The search runs inside one listing walk, so a tree too large for a
        single listing is searched as far as that walk reached.
        """
        parent = _normalize_path(path)
        listing = await self._volumes.list_volume_files(id=self.id, path=parent, search=query)
        needle = query.lower()
        # The API prunes the tree to matches plus the directories holding them;
        # keep only the entries that match so callers get the hits alone.
        return [
            file
            async for file in self._walk_entries(parent, listing.entries, follow_truncated=False)
            if needle in file.name.lower()
        ]

    async def read_file(
        self, path: str, *, offset: int | None = None, length: int | None = None
    ) -> bytes:
        """Read a file's bytes. `offset` and `length` read a slice of it instead of the whole file."""
        ranged = offset is not None or length is not None
        content = await self._volumes.read_volume_file(
            id=self.id,
            path=_normalize_path(path),
            range=_byte_range_header(offset or 0, length) if ranged else None,
        )
        return content.data

    async def read_text(
        self,
        path: str,
        *,
        offset: int | None = None,
        length: int | None = None,
        encoding: str = "utf-8",
    ) -> str:
        """Read a file as text."""
        return (await self.read_file(path, offset=offset, length=length)).decode(encoding)

    async def stream(
        self, path: str, *, chunk_size: int = DEFAULT_CHUNK_BYTES
    ) -> AsyncIterator[bytes]:
        """Read a file in chunks, so a large one never lands in memory whole.

        Each chunk is its own ranged request.
        """
        file_path = _normalize_path(path)
        offset = 0

        while True:
            content = await self._volumes.read_volume_file(
                id=self.id,
                path=file_path,
                range=_byte_range_header(offset, chunk_size),
            )
            if content.data:
                yield content.data

            # An empty file comes back whole, with no Content-Range to page from.
            if content.content_range is None:
                return

            offset = content.content_range.end + 1
            if offset >= content.content_range.size:
                return

    # Depth-first over a listing's nested entries. `follow_truncated` lists the
    # directories the server's walk left unread, which `iterdir` wants and
    # `search` does not: listing one of those directly would drop the search
    # term and pull in everything under it.
    async def _walk_entries(
        self,
        parent: str,
        entries: builtins.list[VolumeFileEntry],
        *,
        follow_truncated: bool,
    ) -> AsyncIterator[VolumeFile]:
        for entry in entries:
            file = VolumeFile(entry, parent)
            yield file
            if not file.is_directory:
                continue
            if entry.entries is not None:
                async for nested in self._walk_entries(
                    file.path, entry.entries, follow_truncated=follow_truncated
                ):
                    yield nested
            elif file.truncated and follow_truncated:
                async for nested in self.iterdir(file.path):
                    yield nested
