# Generated by oagen. DO NOT EDIT.


from __future__ import annotations

import builtins

from porter_sandbox._models import VolumeObjectSpec, VolumeSpec
from porter_sandbox.enums import VolumeSpecType
from porter_sandbox.resources.volumes import AsyncVolumes as AsyncVolumesResource
from porter_sandbox.resources.volumes import Volumes as VolumesResource
from porter_sandbox.volume import (
    AsyncObjectVolume,
    AsyncVolume,
    ObjectVolume,
    Volume,
    _wrap_async_volume,
    _wrap_volume,
)


class Volumes:
    """User-facing volumes namespace under `Porter`."""

    def __init__(self, resource: VolumesResource) -> None:
        self._resource = resource

    @property
    def raw(self) -> VolumesResource:
        """Direct access to the generated low-level volumes resource."""
        return self._resource

    def create(
        self,
        *,
        name: str | None = None,
        type: VolumeSpecType | None = None,
        object: VolumeObjectSpec | None = None,
    ) -> Volume | ObjectVolume:
        spec = VolumeSpec(
            name=name,
            type=type,
            object=object,
        )
        record = self._resource.create_volume(body=spec)
        return _wrap_volume(record, self._resource)

    def list(self) -> builtins.list[Volume | ObjectVolume]:
        response = self._resource.list_volumes()
        return [_wrap_volume(r, self._resource) for r in response.volumes]

    def get(self, name: str) -> Volume | ObjectVolume:
        ref = self._resource.lookup_volume(name=name)
        record = self._resource.get_volume(id=ref.id)
        return _wrap_volume(record, self._resource)

    def delete(self, name: str) -> None:
        ref = self._resource.lookup_volume(name=name)
        self._resource.delete_volume(id=ref.id)
        return None


class AsyncVolumes:
    """User-facing async volumes namespace under `AsyncPorter`."""

    def __init__(self, resource: AsyncVolumesResource) -> None:
        self._resource = resource

    @property
    def raw(self) -> AsyncVolumesResource:
        """Direct access to the generated low-level async volumes resource."""
        return self._resource

    async def create(
        self,
        *,
        name: str | None = None,
        type: VolumeSpecType | None = None,
        object: VolumeObjectSpec | None = None,
    ) -> AsyncVolume | AsyncObjectVolume:
        spec = VolumeSpec(
            name=name,
            type=type,
            object=object,
        )
        record = await self._resource.create_volume(body=spec)
        return _wrap_async_volume(record, self._resource)

    async def list(self) -> builtins.list[AsyncVolume | AsyncObjectVolume]:
        response = await self._resource.list_volumes()
        return [_wrap_async_volume(r, self._resource) for r in response.volumes]

    async def get(self, name: str) -> AsyncVolume | AsyncObjectVolume:
        ref = await self._resource.lookup_volume(name=name)
        record = await self._resource.get_volume(id=ref.id)
        return _wrap_async_volume(record, self._resource)

    async def delete(self, name: str) -> None:
        ref = await self._resource.lookup_volume(name=name)
        await self._resource.delete_volume(id=ref.id)
        return None
